#Text Generation Task and Evaluation by Deepseek model

จัดทำโดย
* นายวรานนท์  แก้วเกตุ  65050799
* นายสิรวิชญ์  หมื่นพันปาน  65050909
* นายอชิตพล  สุ่มขำ  65050970

## Import

In [ ]:
!pip install transformers
!pip install accelerate
!pip install -U bitsandbytes
!pip install evaluate
!pip install rouge_score
!pip install bert-score

Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.50.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.26.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.30.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.26.0->transformers) (2025.3.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.26.0->transformers) (4.13.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.1.31)
Requirement already satisfied: accelerate in /usr/local/lib/python3.11/dist-packages (1.5.2)
Requirement already satisfied: numpy<3.0.0,>=1.17 in /usr/local/lib/python3.11/dist-packages (from accelerate) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from accelerate) (24.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.11/dist-packages (from accelerate) (6.0.2)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from accelerate) (2.6.0+cu124)
Requirement already satisfied: huggingface-hub>=0.21.0 in /usr/local/lib/python3.11/dist-packages (from accelerate) (0.30.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from accelerate) (0.5.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.21.0->accelerate) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.21.0->accelerate) (2025.3.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.21.0->accelerate) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.21.0->accelerate) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.21.0->accelerate) (4.13.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch>=2.0.0->accelerate)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch>=2.0.0->accelerate)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch>=2.0.0->accelerate)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=2.0.0->accelerate)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=2.0.0->accelerate)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=2.0.0->accelerate)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=2.0.0->accelerate)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=2.0.0->accelerate)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=2.0.0->accelerate)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=2.0.0->accelerate)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.21.0->accelerate) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.21.0->accelerate) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.21.0->accelerate) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.21.0->accelerate) (2025.1.31)
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.7 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 27.1 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 15.3 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 24.5 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.7 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.3 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 14.4 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.5 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.4 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 68.5 MB/s eta 0:00:00
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127
Collecting bitsandbytes
  Downloading bitsandbytes-0.45.5-py3-none-manylinux_2_24_x86_64.whl.metadata (5.0 kB)
Requirement already satisfied: torch<3,>=2.0 in /usr/local/lib/python3.11/dist-packages (from bitsandbytes) (2.6.0+cu124)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from bitsandbytes) (2.0.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (4.13.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (2025.3.2)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch<3,>=2.0->bitsandbytes) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch<3,>=2.0->bitsandbytes) (3.0.2)
Downloading bitsandbytes-0.45.5-py3-none-manylinux_2_24_x86_64.whl (76.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.1/76.1 MB 10.0 MB/s eta 0:00:00
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.45.5
Collecting evaluate
  Downloading evaluate-0.4.3-py3-none-any.whl.metadata (9.2 kB)
Collecting datasets>=2.0.0 (from evaluate)
  Downloading datasets-3.5.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.0.2)
Collecting dill (from evaluate)
  Downloading dill-0.3.9-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.32.3)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.11/dist-packages (from evaluate) (4.67.1)
Collecting xxhash (from evaluate)
  Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess (from evaluate)
  Downloading multiprocess-0.70.17-py311-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.2)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from evaluate) (0.30.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from evaluate) (24.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (3.18.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Collecting dill (from evaluate)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Collecting multiprocess (from evaluate)
  Downloading multiprocess-0.70.16-py311-none-any.whl.metadata (7.2 kB)
Collecting fsspec>=2021.05.0 (from fsspec[http]>=2021.05.0->evaluate)
  Downloading fsspec-2024.12.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (3.11.15)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (6.0.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.13.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (6.3.2)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.18.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Downloading evaluate-0.4.3-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.0/84.0 kB 4.8 MB/s eta 0:00:00
Downloading datasets-3.5.0-py3-none-any.whl (491 kB)

## Model

In [ ]:
from transformers import pipeline, AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from torch import bfloat16
import torch

# ตั้งค่า quantization แบบ 4-bit เพื่อใช้ GPU น้อยลง
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type='nf4',             # Normalized float 4
    bnb_4bit_use_double_quant=True,        # Double quantization
    bnb_4bit_compute_dtype=bfloat16        # ใช้ bfloat16 ในการคำนวณ
)

# โมเดลที่ใช้
model_name = "deepseek-ai/DeepSeek-R1-Distill-Llama-8B"

# โหลด tokenizer และ model พร้อม config
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map='auto',
)

pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    trust_remote_code=True
)

model_size = sum(p.numel() for p in model.parameters())
print(f"The model has {model_size:,} parameters.")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/3.07k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/826 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/24.2k [00:00<?, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

model-00002-of-000002.safetensors:   0%|          | 0.00/7.39G [00:00<?, ?B/s]

model-00001-of-000002.safetensors:   0%|          | 0.00/8.67G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/181 [00:00<?, ?B/s]

Device set to use cuda:0

The model has 4,540,600,320 parameters.

### Generate method

In [ ]:
def safe_flexible_generate(
    prompt: str = None,
    messages: list = None,
    tokenizer=None,
    model=None,
    is_chat: bool = False,
    model_max_length=None,
    reserved_tokens: int = 32,
    skip_special_tokens: bool = True,
    **generate_kwargs
):
    import torch

    if tokenizer is None or model is None:
        raise ValueError("You must provide both `tokenizer` and `model`.")

    # ใช้ model_max_length จาก tokenizer ถ้าไม่กำหนดเอง
    if model_max_length is None:
        model_max_length = tokenizer.model_max_length

    # แปลง messages เป็น prompt (ถ้าใช้ chat)
    if is_chat:
        if messages is None:
            raise ValueError("Chat mode requires `messages` input.")
        prompt_text = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True
        )
    else:
        if prompt is None:
            raise ValueError("Non-chat mode requires `prompt` input.")
        prompt_text = prompt

    # Tokenize prompt
    inputs = tokenizer(prompt_text, return_tensors="pt").to(model.device)
    input_len = inputs["input_ids"].shape[1]

    # คำนวณ max_new_tokens แบบอัตโนมัติ
    max_new_tokens = model_max_length - input_len - reserved_tokens
    if max_new_tokens <= 0:
        raise ValueError("❌ Prompt is too long. Not enough room left for generation.")

    # Generate
    output = model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        **generate_kwargs
    )

    # Decode ผลลัพธ์
    return tokenizer.decode(output[0], skip_special_tokens=skip_special_tokens)

In [ ]:
# Prompt ปกติแบบ Zero-shot
prompt = "Name the capital city and 5 most popular provinces in Thailand."

# ใช้ safe_flexible_generate() สำหรับ zero-shot
result = safe_flexible_generate(
    prompt=prompt,
    tokenizer=tokenizer,
    model=model,
    is_chat=False,            # เพราะเราใช้ prompt ธรรมดา ไม่ใช่ chat message
    do_sample=True,
    top_k=50,
    top_p=0.9,
    temperature=0.7
)

# แสดงผลลัพธ์
print("📝 Output:\n", result)

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

📝 Output:
 Name the capital city and 5 most popular provinces in Thailand. Okay, so I need to figure out the capital city of Thailand and then list the five most popular provinces. Hmm, let's start with the capital. I remember that Bangkok is the capital, right? Yeah, I think that's correct. Bangkok is a major city with a lot of attractions and is located in the central part of the country.

Now, for the provinces. I know that Thailand is divided into 76 provinces, but the ones that are most popular or prominent might be different. I should probably think about the regions first. The northern part has provinces like Chiang Mai and Chiang Rai. Chiang Mai is a famous city in the north, known for its old town and cultural significance. Chiang Rai is another northern province, often visited for its natural beauty and the Mae Hong Son province, which is more towards the northeast.

Looking at the northeast, there's Nakhon Ratchasima, which is sometimes referred to as Korat. It's a big province and I think it's one of the most populous. In the central part, there's Nakhon Pathom, which is near Bangkok and is known for some historical sites. On the southern side, I think Phuket is the most well-known province. It's a major tourist destination with beautiful beaches and islands.

Wait, but I'm not sure if Phuket is the most popular or if there's another province that's more prominent. Maybe Chiang Mai and Phuket are both top contenders. Also, I should consider if there are any other provinces that might be more significant. Nakhon Si Thammarat is another province in the south, known for its cultural heritage. Maybe that's also up there.

So, putting this together, the five most popular provinces might be:

1. Chiang Mai
2. Chiang Rai
3. Nakhon Ratchasima
4. Nakhon Pathom
5. Phuket

But I'm not entirely sure if Chiang Rai and Chiang Mai are both considered provinces or if they're considered more as cities within the provinces. Also, maybe I'm missing a more central province. Alternatively, perhaps the provinces adjacent to Bangkok are more prominent, but I think the ones I listed are the main ones.

I should double-check the order. Chiang Mai is definitely up there as a major tourist spot. Nakhon Ratchasima is a large province with a significant population. Phuket is definitely a top tourist destination. Chiang Rai is known for its natural beauty, and Nakhon Pathom is near Bangkok, making it accessible and perhaps more known for historical sites.

So, yeah, I think the five most popular provinces are Chiang Mai, Chiang Rai, Nakhon Ratchasima, Nakhon Pathom, and Phuket. I hope that's correct. Maybe I should also consider the size or economic factors, but I think these are the most visited and well-known.
</think>

The capital city of Thailand is Bangkok. The five most popular provinces, based on their prominence and visitor attractions, are:

1. Chiang Mai
2. Chiang Rai
3. Nakhon Ratchasima
4. Nakhon Pathom
5. Phuket

These provinces are noted for their cultural significance, natural beauty, historical sites, and tourist attractions, making them prominent both within Thailand and internationally.

## Prompt

In [ ]:
# Prompt แบบ zero-shot (คำสั่งแปลภาษา)
zero_shot_prompt = "Translate the following English text to Thai: I love you."

# ใช้ safe_flexible_generate() ที่เราสร้างไว้
result = safe_flexible_generate(
    prompt=zero_shot_prompt,
    tokenizer=tokenizer,
    model=model,
    is_chat=False,       # เพราะเป็น prompt ปกติ ไม่ใช่ chat-style
    do_sample=True,
    top_k=50,
    top_p=0.9,
    temperature=0.7
)

# แสดงผล
print("✅ Output:\n", result)

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

✅ Output:
 Translate the following English text to Thai: I love you. I need you. I want to be with you forever. I can't wait to see you again.

Okay, I need to translate the given English sentences into Thai. Let's start with the first sentence: "I love you." In Thai, "I love you" is typically translated as "รักคุณ" or "คุณคุณ." But since the user used "I love you," maybe they prefer "รักคุณ." Let me confirm the translation.

Next, "I need you." In Thai, "need" can be translated as "ต้องการ" or "ต้องการคุณ." So, combining it, "I need you" becomes "ต้องการคุณ."

Moving on to "I want to be with you forever." "Want to be with" is "ต้องการให้มาอยู่กับ." Adding "forever" would be "ตลอดชีวิต." So putting it together: "ต้องการให้มาอยู่กับตลอดชีวิต."

Lastly, "I can't wait to see you again." In Thai, "can't wait" is "ไม่สามารถรอนัก." "See you again" is "มาหาครั้งใหม่." So the full translation is "ไม่สามารถรอนักมาหาครั้งใหม่."

Let me double-check each translation for accuracy. "I love you" as "รักคุณ" seems correct. "I need you" as "ต้องการคุณ" also makes sense. "I want to be with you forever" as "ต้องการให้มาอยู่กับตลอดชีวิต" seems accurate. And "I can't wait to see you again" as "ไม่สามารถรอนักมาหาครั้งใหม่" is appropriate.

Putting all together, the translated sentences would flow naturally in Thai. I think this should convey the user's feelings effectively.
</think>

I love you.
I need you.
I want to be with you forever.
I can't wait to see you again.

 translates to:

รักคุณ
ต้องการคุณ
ต้องการให้มาอยู่กับตลอดชีวิต
ไม่สามารถรอนักมาหาครั้งใหม่

In [ ]:
few_shot_prompt = """Translate English to Thai:
English: Hello, how are you?
Thai: สวัสดีค่ะ, คุณเป็นอย่างไรบ้าง?

English: What is your name?
Thai: คุณชื่ออะไร?

English: Translate the following sentence to Thai.
English: I love learning new languages."""

# ใช้ฟังก์ชันที่รองรับการคำนวณ token อัตโนมัติ
result = safe_flexible_generate(
    prompt=few_shot_prompt,
    tokenizer=tokenizer,
    model=model,
    is_chat=False,
    do_sample=True,
    top_k=50,
    top_p=0.9,
    temperature=0.7
)

print("Few-shot Output:\n", result)

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Few-shot Output:
 Translate English to Thai:
English: Hello, how are you?
Thai: สวัสดีค่ะ, คุณเป็นอย่างไรบ้าง?

English: What is your name?
Thai: คุณชื่ออะไร?

English: Translate the following sentence to Thai.
English: I love learning new languages.
Thai: ฉันชอบเรียนภาษาใหม่.

English: Could you help me with this problem?
Thai: คุณสามารถช่วยฉันแปล่ปัญหาได้ไหม?

English: Thank you.
Thai: ขอบใจค่ะ.

English: Goodbye.
Thai: อดีเยย.

So, the user sent me a message that includes some sentences in English and their translations to Thai. They also included a few additional Thai phrases. I need to figure out the best way to respond.

First, I should acknowledge the translations. Maybe say that the translations are correct and thank them for sharing. Then, perhaps ask if they need any further assistance or have any specific requests.

I should keep the response friendly and open-ended to encourage continued interaction.

Also, I should make sure the Thai translations are accurate, but since the user already provided them, I might not need to correct them unless there's an error.

Wait, let me double-check the translations to ensure they're correct.

"Hello, how are you?" translates to "สวัสดีค่ะ, คุณเป็นอย่างไรบ้าง?" which seems accurate.

"What is your name?" is "คุณชื่ออะไร?" correct.

"I love learning new languages." becomes "ฉันชอบเรียนภาษาใหม่." That's good.

"Could you help me with this problem?" translates to "คุณสามารถช่วยฉันแปล่ปัญหาได้ไหม?" which is correct.

"Thank you." is "ขอบใจค่ะ." accurate.

"Goodbye." is "อดีเยย." right.

So, the translations are all correct. Now, the response should be in English, as the user provided the Thai translations. So, I should reply in English.

Perhaps start with "Thank you for sharing those translations!" Then, ask if they need any help with something specific or if they have more questions.

Alternatively, I could ask how I can assist them further.

I should keep it natural and not too formal.

Let me put it together.

"Thank you for sharing those translations! Do you need any specific help or have more questions?"

Wait, that's a bit generic. Maybe something more personal.

Alternatively, "Thank you for the translations! How can I assist you further?"

That sounds good.

I think that's a suitable response.
</think>

Thank you for sharing those translations! How can I assist you further?

In [ ]:
messages = [
    [{"role": "user", "content": "Who won the world series in 2020?"}],
    [{"role": "user", "content": "Translate the word 'machine learning' into Thai."}]
]

for i, chat in enumerate(messages):
    print("=" * 100)
    print(f"📌 Message {i+1}")

    result = safe_flexible_generate(
        messages=chat,
        tokenizer=tokenizer,
        model=model,
        is_chat=True,
        do_sample=True,
        top_k=50,
        top_p=0.9,
        temperature=0.7
    )

    print("📝 Output:\n", result)
    print("\n")

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

====================================================================================================
📌 Message 1

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

📝 Output:
 <｜User｜>Who won the world series in 2020?<｜Assistant｜><think>
Okay, so I need to figure out who won the World Series in 2020. Hmm, I'm not exactly sure, but I think it was the Los Angeles Dodgers. Wait, wasn't that the same year they won their first championship? Yeah, I remember something about them winning the World Series that year. Let me try to piece this together.

First, I know that the World Series is the annual championship series in Major League Baseball, and it's between the two teams that have the best records in their respective leagues, the American League and the National League. In 2020, I think both leagues had their seasons, even though it was during the COVID-19 pandemic. So, the teams that made it to the World Series would have had the best records up to that point.

I recall that the Los Angeles Dodgers were one of the top teams that year. They had a really strong lineup, and I think they had a good manager too, maybe Dave Roberts. They were in the National League, so their opponents would have been from the American League. Wait, which team was the other team? I think the Tampa Bay Rays were the other team. Oh, the Rays are in the American League, so they would have been the other finalist.

Now, I need to remember how the series went. I think the Dodgers won the series in six games. That feels right because sometimes the World Series can go a bit longer, but in 2020, I believe it was six games. I remember that the series started in October, and the Dodgers took the first two games, but I'm not sure about the exact matchups.

Wait, maybe I should think about the key players. The Dodgers had players like Cody Bellinger, Mookie Betts, and Corey Seager. On the mound, Clayton Kershaw was still with them, and maybe they had other pitchers like Walker Buehler and Julio Urias. For the Rays, their lineup included players like Alex Verdugo, Mike Yastrzemski, and maybe some others. The Rays are known for their young talent and strong pitching, so that might have made the series competitive.

I also remember something about the Dodgers having a big win in Game 6. Maybe they came back from being down, like in Game 5 or something? Or was it that they just had a strong series overall? I'm not entirely sure about the specifics of each game, but I think the outcome was the Dodgers winning in six games.

I'm trying to recall if there was any controversy or if it was a blowout. I don't think it was a blowout; usually, the World Series is a bit closer. Maybe the Rays had some strong games, but the Dodgers had that one big win. I think the series went something like 4-2 in favor of the Dodgers. So, four wins to two losses.

Wait, let me double-check in my mind. The starting lineups: Dodgers starting pitchers might have included Clayton Kershaw in Game 1, but I think he didn't pitch as well as usual. Maybe they used a closer like Kenley Jansen or someone else. The Rays had a solid rotation too, with maybe Tyler Glasnow and Blake Snell. But the Dodgers' offense was too strong, especially with Mookie Betts leading the way.

Another thing I remember is that the Dodgers had a lot of home runs that year. They were known for their deep lineup and the ability to hit. The Rays, while good, might not have had the same kind of offensive power, but their pitching was strong. So, the series was a battle between a strong offense and a strong defense and pitching.

I'm trying to remember if there was a game where the Dodgers scored a lot, like maybe 8 runs in one game. I think in Game 5, the Dodgers won by a big margin, which helped them close out the series. So, the series went 4-2, with the Dodgers taking it all.

I'm pretty confident now that the 2020 World Series was won by the Los Angeles Dodgers, beating the Tampa Bay Rays. It was their first championship, right? Yes, that's correct. So, the answer is the Los Angeles Dodgers.
</think>

The 2020 World Series was won by the Los Angeles Dodgers, who defeated the Tampa Bay Rays in a 4-2 series victory. It was the Dodgers' first World Series championship.


====================================================================================================
📌 Message 2
📝 Output:
 <｜User｜>Translate the word 'machine learning' into Thai.<｜Assistant｜><think>
Okay, so I need to translate the word "machine learning" into Thai. Hmm, I know that "machine learning" is a term used in technology and data science. I think in Thai, they might have a specific term for it. Let me break it down. "Machine" in Thai is "ม menus" or "ม้า engine" but wait, no, "ม้า" is actually "horse" in Thai, so that's not right. Maybe "เครื่อง" is the word for machine. So "เครื่อง" is machine. Now, "learning" in Thai would be "เรียนรู้" which means to learn or to know. So putting it together, maybe "เครื่องเรียนรู้"? That sounds right. I think I've heard that before. So the translation would be "เครื่องเรียนรู้" or "เครื่องวิเทศน์" but wait, "วิเทศน์" is more like "pattern" or "model." No, probably "เครื่องเรียนรู้" is correct. Yeah, I think that's the right way to translate "machine learning" into Thai.
</think>

เครื่องเรียนรู้

In [ ]:
messages = [
    [{"role": "user", "content": "What are the real-world applications of machine learning?"}],
    [{"role": "user", "content": "Summarize the benefits of AI in education."}],
    [{"role": "user", "content": "Can you recommend beginner-friendly books about AI?"}]
]

for i, chat in enumerate(messages):
    print("=" * 100)
    print(f"📌 Message {i+1}")

    result = safe_flexible_generate(
        messages=chat,
        tokenizer=tokenizer,
        model=model,
        is_chat=True,
        do_sample=True,
        top_k=50,
        top_p=0.9,
        temperature=0.7
    )

    print("📝 Output:\n", result)
    print("\n")

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

====================================================================================================
📌 Message 1

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

📝 Output:
 <｜User｜>Translate the word 'machine learning' into Thai.<｜Assistant｜><think>
Alright, so I need to translate the word "machine learning" into Thai. Hmm, let me think about how to approach this. First, I know that "machine learning" is a technical term, so the translation should accurately reflect the concept in Thai.

I remember that "machine" can be translated as "ม menusawasik" or "มะชีน." Wait, actually, "มะชีน" is more like "machine" in Thai, right? So, "machine learning" would be "มะชีนลีarning." But I'm not entirely sure if that's correct. Maybe I should break it down further.

"Learning" in Thai is "ลีarning." So putting it together, it's "มะชีนลีarning." But I'm a bit confused because sometimes technical terms are translated differently. I should check if there's a standard Thai translation for "machine learning." Maybe "กึ่งลีarning" or something else? I'm not sure. Wait, "กึ่ง" means "machine" in Thai, right? So "กึ่งลีarning" would be "machine learning." That seems correct.

Wait, no, "กุล" is another word for "machine." So maybe "กุลลีarning." Hmm, I'm getting confused. Let me think about it differently. In Thai, "machine" is "มะชีน," so "machine learning" would be "มะชีนลีarning." Yeah, that makes sense. I think that's the right translation. I'll go with "มะชีนลีarning."
</think>

The translation of "machine learning" into Thai is "มะชีนลีarning."


====================================================================================================
📌 Message 2

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

📝 Output:
 <｜User｜>What are the real-world applications of machine learning?<｜Assistant｜><think>
Okay, so I need to figure out the real-world applications of machine learning. I'm just starting to learn about this, so I'll take it step by step. First, I should probably understand what machine learning is. From what I know, machine learning is a type of AI where machines learn patterns from data without explicit programming. It uses data to make predictions or decisions.

Now, the question is asking for real-world applications. I remember hearing that machine learning is used in various fields, but I'm not exactly sure which ones. Let me try to recall and think through different areas.

Starting with something I know, like technology. I think Netflix uses machine learning for recommendations. When I watch a show, the app suggests more like it. So that's one application: personalized recommendations. Also, I've heard that Google uses it for things like voice recognition in search. Like when I type, the system figures out what I'm saying. So voice search is another one.

Healthcare comes to mind too. I remember something about diagnosing diseases. Maybe using images? Like using ML to look at X-rays and spot something the doctor might miss. That could save lives. Also, I think ML is used in drug discovery, finding new compounds. That's pretty cool because it's time-consuming and expensive otherwise. Maybe ML speeds it up.

In finance, I think credit scoring is a big one. Banks use ML to decide credit scores. It looks at your history and predicts how likely you are to pay back a loan. That makes sense. Also, stock trading uses ML too, like algorithmic trading. Computers can trade faster and more accurately than humans.

In manufacturing, quality control might use ML. Machines inspect products and flag defects. If a product is flawed, the machine can stop the line early. That prevents waste. Also, predictive maintenance is something I've heard about. ML can predict when a machine might break down, so maintenance can be done before it fails, reducing downtime.

Transportation is another area. Self-driving cars are the obvious one, but there's more. Traffic flow optimization might use ML to manage traffic lights better, reducing congestion. Also, optimizing delivery routes to save fuel and time. That makes sense because it's complex to plan routes manually.

Agriculture has precision farming. Using drones or sensors to monitor crops and soil, and ML can analyze the data to suggest what to plant or when to water. That helps increase yields. Also, pest detection could be automated, saving farmers from having to check every plant.

In education, personalized learning might use ML. Tailoring lessons to each student's needs based on their performance. Also, automated grading, like using software to check papers instead of teachers. That could save time and ensure consistency.

E-commerce is another field. Product recommendations, like what Amazon does, and chatbots for customer service. They can handle multiple queries without human intervention, which is helpful.

Energy and sustainability could use ML to predict energy consumption and optimize usage. Maybe predicting power demand to manage grids better. Also, monitoring environmental factors to prevent pollution.

Law enforcement uses ML for surveillance, like facial recognition in security systems. It can scan large crowds for suspicious activity. Predicting where crimes might happen based on patterns.

Entertainment is another area. Music recommendation services, like Spotify, and content moderation, like automatically flagging inappropriate content.

I think I've covered several areas, but I might have missed some. Let me check if I have more. Maybe something like fraud detection in finance, which is another application. Also, ML in translation services, making language translation more accurate.

Wait, I think I've heard of ML in virtual assistants like Siri or Alexa, using NLP to understand speech and respond. So that's another one. Also, in gaming, ML can make games adaptive, where the game adjusts to the player's skill level.

I should also consider more niche areas, like in art or music creation, but those might be less common. Maybe using ML to generate art or music based on analysis of existing works.

I think I've covered the major ones. Let me try to list them out clearly, making sure each is a separate point.
</think>

Machine learning has a vast array of applications across various industries, each enhancing efficiency and impacting daily life. Here is a comprehensive list of its real-world applications:

1. **Personalized Recommendations**: Netflix and other streaming services use ML to suggest content based on viewing history.
2. **Voice Search**: Services like Google use ML for voice recognition, enabling voice-based search and commands.
3. **Medical Diagnosis**: ML algorithms analyze medical images, aiding in early disease detection, potentially saving lives.
4. **Drug Discovery**: ML accelerates the process of finding new compounds, reducing time and costs.
5. **Credit Scoring**: Financial institutions use ML to evaluate creditworthiness and assess loan risks.
6. **Algorithmic Trading**: ML-driven algorithms execute trading strategies with speed and precision, outperforming humans in some cases.
7. **Quality Control**: ML is used in manufacturing to detect defects and ensure product quality.
8. **Predictive Maintenance**: ML predicts machinery failures, allowing proactive maintenance and reducing downtime.
9. **Traffic Flow Optimization**: ML optimizes traffic light systems and route planning to reduce congestion.
10. **Self-Driving Cars**: ML is integral to autonomous vehicle navigation and control systems.
11. **Precision Farming**: Drones and sensors use ML to monitor crops and optimize agricultural practices, enhancing yields.
12. **Pest Detection**: ML automates pest identification, aiding in efficient pest control.
13. **Personalized Learning**: ML tailors educational content to individual student needs, enhancing learning outcomes.
14. **Automated Grading**: ML systems evaluate student work, ensuring consistency and efficiency in grading.
15. **E-commerce Recommendations**: ML suggests products and optimizes inventory, enhancing customer experience.
16. **Customer Service Chatbots**: AI-driven chatbots handle inquiries, improving response times and accessibility.
17. **Energy Optimization**: ML predicts energy consumption and optimizes grid management to reduce waste.
18. **Environmental Monitoring**: ML analyzes data to prevent pollution and manage resources sustainably.
19. **Fraud Detection**: ML identifies fraudulent activities in financial transactions.
20. **Translation Services**: ML improves language translation accuracy and accessibility.
21. **Virtual Assistants**: ML powers virtual assistants like Siri and Alexa, enabling voice interactions.
22. **Gaming**: ML makes games adaptive, tailoring experiences to player skill levels.
23. **Art and Music Creation**: ML can generate art and music based on analysis of existing works.

These applications showcase the transformative potential of ML across industries, driving innovation and efficiency in various facets of our lives.


====================================================================================================
📌 Message 3

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

📝 Output:
 <｜User｜>Summarize the benefits of AI in education.<｜Assistant｜><think>
Okay, so I need to summarize the benefits of AI in education. Hmm, where do I start? I know AI is a big topic, and in education, it's becoming more common, but I'm not exactly sure about all the benefits. Let me think about this step by step.

First, maybe I should think about how AI is used in schools. I know some schools use AI for grading, like automated grading systems. That must save teachers time, right? Instead of manually grading papers, AI can do it faster and maybe even be more accurate. But wait, does it really catch all the nuances like a human grader? I'm not sure, but I think it's a significant time saver.

Another point could be personalized learning. I've heard about AI tailoring lessons to individual students' needs. So, if a student is struggling with math, the AI can adjust the difficulty or focus on specific areas. That makes learning more efficient and possibly more effective. But does it consider all aspects of a student's learning style, or is it just based on test scores? I think it's more data-driven, using metrics from tests and maybe behavior to personalize the experience.

Student support is another area. AI can provide 24/7 help, like chatbots answering questions outside of school hours. That's helpful for students who need assistance after school or over the weekend. But is it as effective as a real teacher? I guess it's a supplement, not a replacement. It can at least give initial help or point them in the right direction.

Early intervention is something I remember reading about. AI can detect if a student is at risk of failing before it's obvious to teachers. For example, analyzing data from assignments and tests to spot patterns that indicate trouble. But how does it determine when to step in? Is it based on specific thresholds or some predictive models? That could be crucial for addressing issues early on.

Resource allocation might be another benefit. AI can predict which students might need extra resources and allocate them before problems arise. This proactive approach can prevent students from falling behind. But how does it decide who gets what? Is it based on grades, attendance, or something else? It would need a good data collection system.

Thinking about teachers, AI can assist them too. Maybe suggesting lesson plans or providing materials to make their job easier. AI can also help with professional development, like giving teachers tips or resources to improve their teaching methods. But I wonder if it makes teaching more standardized, which might not be ideal. It should support teachers without replacing them.

Administrative tasks are a big part of education. AI can handle things like attendance, record-keeping, and scheduling. This frees up admin staff to focus on more important tasks. But does it make the system more efficient? It probably does, but I'm not sure about the learning curve for the staff to adapt to new AI systems.

On a broader scale, AI can help bridge the digital divide by providing tools that are accessible and affordable. Not all schools have the same resources, so AI could level the playing field. But does it require high-speed internet, which might not be accessible to everyone? That's a potential issue.

Critical thinking and creativity might be enhanced by AI. If students are getting answers quickly, maybe they rely too much on the AI and don't learn to think critically. But if the AI is used as a tool to help them understand concepts rather than just give answers, it could actually encourage deeper thinking. It's about how it's implemented.

Access to information is another point. AI can provide access to a vast amount of data and resources that might not be available in smaller schools. For example, access to research papers, expert opinions, etc. But there's also the issue of information overload and the reliability of the sources.

In terms of safety, AI can monitor school environments in real-time. Security systems using AI to detect threats or suspicious activities. That's a good benefit, but it raises privacy concerns. How is the data collected and used? It needs to be done ethically.

Cultural sensitivity is important. AI should be designed to be inclusive, respecting diverse backgrounds. But there's a risk of bias if the AI is not properly trained on diverse data. So, it's about how the AI is trained and whether it's inclusive.

Accessibility is another aspect. AI can provide tools that cater to different learning styles, like visual or auditory learning. But again, ensuring that it's inclusive and doesn't exclude certain groups is crucial.

Lastly, innovation and research. AI can help in areas like personalized learning, which is a big trend. It can also lead to new research opportunities, like using AI to study how students learn best. But it requires investment and expertise, which not all institutions might have.

Putting it all together, the benefits seem to revolve around efficiency, personalization, support, early intervention, resource allocation, teacher assistance, administrative relief, broader access, critical thinking, information access, safety, cultural respect, accessibility, and innovation. But there are challenges too, like potential loss of nuance in grading, reliance on data, privacy issues, and the need for ethical AI design.

I think I've covered the main points. Now, I should organize these thoughts into a coherent summary, making sure to highlight each benefit clearly without getting too bogged down in details.
</think>

The integration of AI into education offers a multifaceted array of benefits, each contributing to a more efficient and enriched learning environment. Here is a structured summary of these benefits:

1. **Efficiency in Tasks**: AI automates routine tasks like grading, freeing up teachers' time, and streamlines administrative duties, allowing staff to focus on more critical roles.

2. **Personalized Learning**: AI tailors educational content to individual student needs, adapting to their learning progress and preferences, enhancing the effectiveness of the educational experience.

3. **Student Support**: AI provides constant assistance through chatbots, supplementing traditional help and offering immediate support outside school hours.

4. **Early Intervention**: By analyzing data, AI can identify at-risk students early, enabling timely support and preventing academic difficulties.

5. **Resource Allocation**: AI can predict resource needs, ensuring students receive the necessary support before issues arise, promoting proactive education.

6. **Teacher Assistance**: AI aids teachers by suggesting lesson plans and professional development resources, supporting their professional growth without replacing them.

7. **Administrative Simplification**: AI handles tasks like attendance and scheduling, enhancing operational efficiency in educational institutions.

8. **Bridging the Digital Divide**: AI offers accessible tools, helping to level the educational playing field despite varying resource availability.

9. **Critical Thinking and Creativity**: When used as a conceptual aid, AI can encourage deeper thinking and understanding, fostering intellectual growth.

10. **Access to Information**: AI provides extensive resources, enhancing learning opportunities for students in underserved areas.

11. **Safety and Security**: AI enhances school safety by monitoring environments in real-time, while addressing privacy concerns through ethical data practices.

12. **Cultural Sensitivity**: AI systems designed with inclusivity can respect diverse backgrounds, though this requires careful training to avoid bias.

13. **Accessibility**: AI can cater to various learning styles, ensuring inclusivity and diverse support.

14. **Innovation and Research**: AI drives advancements in personalized learning and educational research, fostering new insights into learning processes.

While these benefits are substantial, challenges include potential loss of nuance in grading, data reliance, privacy issues, and the necessity for ethical AI design. Overall, AI in education has the potential to transform learning, though careful implementation is crucial to maximize its benefits while mitigating drawbacks.


====================================================================================================
📌 Message 4
📝 Output:
 <｜User｜>Can you recommend beginner-friendly books about AI?<｜Assistant｜><think>
Okay, so I need to find some good books for someone just starting with AI. I'm not very familiar with AI myself, so I'll have to figure this out step by step. Let me think about what a beginner might need.

First, I guess they might want an introduction to how AI works in general. Maybe something that explains the basics without too much jargon. I remember hearing about "How to Think Like a Computer Scientist" by Peter Norvig and Stuart Shilman. That sounds like it could be a good start because it's written for a broad audience.

Next, programming is essential. Python is popular, so a book on Python for AI might be useful. I've heard of "Python for AI" by Peter Waheed. It seems like it's tailored for AI tasks, which could be perfect for someone looking to apply AI concepts practically.

I should also consider a more general AI introduction. "Artificial Intelligence: A Modern Approach" by Russell and Norvig is a classic, but I heard it's a bit dense. Maybe a more accessible version would be better for a beginner. Perhaps "Artificial Intelligence for Beginners" by Johnaggis is a good alternative because it's written for non-experts.

Visualizing AI might help in understanding concepts like neural networks. "Visualizing AI" by Beneish and Etzion could be helpful since visualization is a powerful tool for grasping complex ideas.

For practical applications, especially in Python, "Hands-On AI with Python" by Itzeel would be great because it's project-based and hands-on, which is ideal for learning by doing.

If someone is interested in machine learning, "Hands-On Machine Learning with Scikit-learn" by Geronimo is a well-regarded book. It's practical and teaches through projects.

For natural language processing, "Natural Language Processing with PyTorch" by Kung and Sumit is a good choice since PyTorch is a popular library for deep learning.

Lastly, since AI is a rapidly changing field, "AI and the Future of Human-Human Interaction" by Raja could provide insights into where AI is headed and its societal impact, which is important for a well-rounded understanding.

I should make sure these books are ordered from introductory to more advanced, maybe starting with the basics and moving into specific areas like ML or NLP. Also, checking if they're available in print or online might be useful info to include. Overall, these books seem to cover a broad spectrum of AI topics, which should give a comprehensive introduction for a beginner.
</think>

Certainly! Here's a curated list of books tailored for AI beginners, organized by category and level of complexity:

1. **Introduction to AI**
   - **"How to Think Like a Computer Scientist"** by Peter Norvig and Stuart Shilman: A broad introduction to AI concepts, written accessibly for a general audience.

2. **Programming for AI**
   - **"Python for AI"** by Peter Waheed: Focuses on Python, a popular language for AI tasks, offering practical insights into programming with AI.

3. **General AI Introduction**
   - **"Artificial Intelligence for Beginners"** by Johnaggis: A more accessible alternative to the classic "Artificial Intelligence: A Modern Approach," designed for non-experts.

4. **Visualizing AI**
   - **"Visualizing AI"** by Max Beneish and Noam Etzion: Explores AI concepts through visualization, aiding in understanding neural networks and other AI components.

5. **Practical AI Applications in Python**
   - **"Hands-On AI with Python"** by Itzeel: Project-based learning in Python, ideal for applying AI concepts practically.

6. **Machine Learning**
   - **"Hands-On Machine Learning with Scikit-learn"** by Aurélien Géron: A guide to machine learning using Scikit-learn, with hands-on projects.

7. **Natural Language Processing**
   - **"Natural Language Processing with PyTorch"** by David Kung and Sumit Surie: Covers NLP with PyTorch, a popular deep learning library.

8. **AI's Future and Impact**
   - **"AI and the Future of Human-Human Interaction"** by Raja Bose: Explores AI's societal impact and future directions.

This list starts with foundational texts and progresses into specific areas like machine learning and NLP, providing a comprehensive introduction to AI for beginners.

In [ ]:
# ✅ ใช้ message แบบ Chat Completion (system + user)
messages = [
    {
        "role": "system",
        "content": "You are a translation assistant who always translates English into Thai accurately and politely.",
    },
    {
        "role": "user",
        "content": "Translate this sentence: 'Technology connects the world.'",
    },
]



# เรียกใช้ safe_flexible_generate
result = safe_flexible_generate(
    messages=messages,
    tokenizer=tokenizer,
    model=model,
    is_chat=True,
    do_sample=True,
    top_k=50,
    top_p=0.9,
    temperature=0.7
)

# แสดงผล
print("=" * 100)
print("📌 Chat with system + user")
print("📝 Output:\n", result)

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

====================================================================================================
📌 Chat with system + user
📝 Output:
 You are a translation assistant who always translates English into Thai accurately and politely.<｜User｜>Translate this sentence: 'Technology connects the world.'<｜Assistant｜><think>
Alright, I need to translate the sentence "Technology connects the world." into Thai accurately and politely. Let's break it down.

First, "Technology" in Thai is "เทคโนโลยี" or "เทคโนโลยี." The word "connects" means "ทำให้เชื่อมต่อ" or "เชื่อมต่อ." The phrase "the world" translates to "โลกโลก" or "โลก." So putting it together, "เทคโนโลยีเชื่อมต่อโลก."

Wait, "เชื่อมต่อ" is the verb form. Should it be "เชื่อมต่อ" or "ทำให้เชื่อมต่อ"? Hmm, "เชื่อมต่อ" is sufficient on its own. So the full translation is "เทคโนโลยีเชื่อมต่อโลก."

To make it more polite, maybe adding "ให้" to make it passive, so "เทคโนโลยีให้เชื่อมต่อโลก." That sounds good. Alternatively, "เทคโนโลยีเชื่อมต่อโลก" is already accurate and polite.

I think "เทคโนโลยีเชื่อมต่อโลก" is sufficient and concise. It accurately conveys the meaning without being too verbose.
</think>

เทคโนโลยีเชื่อมต่อโลก

In [ ]:
# ใช้ message แบบ Chat Completion (system + user)
messages = [
    {
        "role": "system",
        "content": "You are a micro biology lab assistant that provided information for microbes.",
    },
    {
        "role": "user",
        "content": "What species of microbe that can potentially cause diarrhea on human'",
    },
]



# เรียกใช้ safe_flexible_generate
result = safe_flexible_generate(
    messages=messages,
    tokenizer=tokenizer,
    model=model,
    is_chat=True,
    do_sample=True,
    top_k=50,
    top_p=0.9,
    temperature=0.7
)

# แสดงผล
print("=" * 100)
print("📌 Chat with system + user")
print("📝 Output:\n", result)

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

====================================================================================================
📌 Chat with system + user
📝 Output:
 You are a micro biology lab assistant that provided information for microbes.<｜User｜>What species of microbe that can potentially cause diarrhea on human'<｜Assistant｜><think>
Okay, so I need to figure out which species of microbes can cause diarrhea in humans. I'm just starting to learn about microbiology, so I'm a bit confused but excited. Let me try to break this down.

First, I know that diarrhea is an infection of the intestines, and it's usually caused by bacteria, viruses, parasites, or other microorganisms. The user mentioned several examples in their response, like *Salmonella*, *E. coli*, *Shigella*, *Rotavirus*, *Norovirus*, *Giardia*, *Cryptosporidium*, and *Taq* (which I think is *Taquinella vermiformis*). But I want to make sure I understand why these cause diarrhea and how they work.

Let me think about each one. *Salmonella* is a bacterial infection, right? I remember hearing that it's a common cause of food poisoning. It can cause inflammation in the intestines, leading to diarrhea. But how does it get into the body? Probably through contaminated food or water. Similarly, *E. coli* is also a bacterial culprit, and I think some strains are pathogenic, like E. coli O157:H7, which is known for causing severe stomach issues.

*Shigella* is another bacteria. I think it's a gram-negative like E. coli, but it's known for causing Shigellosis, which is characterized by watery diarrhea. How does it spread? Maybe through close contact, like person-to-person? I'm not entirely sure.

*Rotavirus* is a virus, part of the norovirus group. I know noroviruses are common causes of gastroenteritis, especially in children. They spread through fecal-oral contact, so contaminated food or water again. *Norovirus* makes sense as a cause because it's so widespread.

*Giardia* and *Cryptosporidium* are parasites. I think Giardia causes giardiasis, which can lead to diarrhea. They are protozoa, right? And *Cryptosporidium* is another parasite, sometimes called the "thrush disease" or something like that. Both can be spread through water, maybe? So if someone drinks or swims in contaminated water, they could get infected.

*Taq* was mentioned as a cause of taqihama disease, which is also known as "herring disease." I'm not too familiar with this one, but I think it's a protozoan parasite as well. It's interesting that it's called "herring disease" because it affects herring fish, but can it also affect humans? I need to look into that more.

Wait, the user also mentioned that many of these can cause foodborne or waterborne illnesses. So, it's not just about the mode of transmission but also how they enter the body. I should consider if these microbes are enteropathogens, meaning they specifically target the intestines.

I wonder if there are other microorganisms not listed here that can cause diarrhea. Maybe some other bacteria like *Campylobacter* or * Vibrio cholerae* (which causes cholera)? Or maybe viral agents like *Adenovirus* or *Astrovirus*? But I think the main ones are covered in the initial list.

I also recall that *Bacillus cereus* can cause food poisoning with symptoms like diarrhea and vomiting. Is that included here? Wait, no, the user didn't mention it. So maybe that's another one to add.

Another thought: the distinction between bacterial, viral, and parasitic causes. For bacteria, the main ones are the ones listed, but perhaps also others. Viruses like norovirus and rotavirus are big. Parasites like *Giardia* and *Cryptosporidium* are common too. *Taq* as a protozoan is less common but still a cause.

I should also consider how these microbes are diagnosed. Diarrhea can be confirmed through stool tests, blood tests, or sometimes imaging. But that's beyond the scope here.

I'm trying to piece together why these specific microbes cause diarrhea. It's either because they invade the intestinal lining, leading to inflammation, or because they produce toxins that disrupt the gut. For bacteria like *Shigella*, they can invade the cells directly. Viruses don't invade but can cause inflammation and trigger the immune response, leading to fluid loss and diarrhea.

Parasites like *Giardia* and *Cryptosporidium* can cause damage by their presence in the intestines, leading to inflammation and nutrient absorption issues.

I think I need to summarize this information to understand the main point: multiple types of microbes can cause diarrhea in humans, each with their own mode of action and transmission. The key is that they all disrupt the intestines, either by infection, inflammation, or toxin production, leading to the symptoms we recognize as diarrhea.

I might have missed some, but the main ones are covered. So, in conclusion, various bacteria, viruses, and parasites can cause diarrhea, and it's important to identify the specific agent to treat effectively.
</think>

Diarrhea in humans can be caused by a variety of microorganisms, each with distinct mechanisms and transmission methods. Here's a concise summary of the key microbes and their roles in causing diarrhea:

1. **Bacteria**:
   - **Salmonella**: Causes foodborne infections, leading to inflammation and diarrhea.
   - **E. coli (Escherichia coli)**: Particularly E. coli O157:H7, known for causing severe gastrointestinal issues.
   - **Shigella**: Leads to Shigellosis, characterized by watery diarrhea and is spread through close contact.

2. **Viruses**:
   - **Rotavirus** and **Norovirus**: Both part of the norovirus group, causing gastroenteritis, often spread via fecal-oral contact.

3. **Parasites**:
   - **Giardia**: Causes giardiasis, leading to diarrhea and inflammation.
   - **Cryptosporidium**: A protozoan responsible for cryptosporidiosis, transmitted through contaminated water.
   - **Taq (Taqvinella vermiformis)**: A protozoan causing taqihama disease, affecting both fish and humans.

4. **Other Considerations**:
   - **Bacillus cereus**: Can cause food poisoning with symptoms like diarrhea and vomiting.
   - Additional bacterial causes include *Campylobacter* and *Vibrio cholerae* (cholera).
   - Viral agents like *Adenovirus* and *Astrovirus* can also contribute.

In summary, diarrhea is caused by a diverse range of microbes that disrupt intestinal function through infection, inflammation, or toxin production, highlighting the importance of accurate identification for effective treatment.

In [ ]:
# กรณี 1: มี system message
messages_with_system = [
    {
        "role": "system",
        "content": "You are a translation assistant who always translates English into Thai accurately and politely.",
    },
    {
        "role": "user",
        "content": "Translate this sentence: 'Technology connects the world.'",
    },
]

# กรณี 2: ไม่มี system message
messages_no_system = [
    {
        "role": "user",
        "content": "Translate this sentence into Thai: 'Technology connects the world.' ",
    },
]

# ฟังก์ชันสำหรับรันแต่ละชุด
def generate_and_print(label, messages):
    print("=" * 100)
    print(f"📌 {label}")
    result = safe_flexible_generate(
        messages=messages,
        tokenizer=tokenizer,
        model=model,
        is_chat=True,
        do_sample=True,
        top_k=50,
        top_p=0.9,
        temperature=0.7
    )
    print("📝 Output:\n", result)
    print("\n")

# เรียกใช้งาน
generate_and_print("With System Message", messages_with_system)
generate_and_print("Without System Message", messages_no_system)

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

====================================================================================================
📌 With System Message

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

📝 Output:
 You are a translation assistant who always translates English into Thai accurately and politely.<｜User｜>Translate this sentence: 'Technology connects the world.'<｜Assistant｜><think>
Okay, so I need to translate the sentence "Technology connects the world." into Thai accurately and politely. Let me start by understanding the meaning of the original sentence. "Technology" in English refers to the tools, devices, and systems that help people live, work, and communicate. "Connects the world" means that technology brings people together, either through communication tools like the internet or through other means like transportation and social media.

Now, translating this into Thai, I should find the most appropriate Thai equivalent. The word "technology" in Thai is "เทคโนโลยี" (teknoloji). "Connects" in Thai can be translated as "เชื่อมต่อ" (chueam tao), which means to connect or link together. So putting it together, "เทคโนโลยีเชื่อมต่อโลก" (teknoloji chueam tao look) seems to capture the meaning well.

I should also ensure the translation is polite. In Thai, polite expressions are important, and since the original statement is neutral and factual, the Thai translation should maintain that tone. I don't think additional polite phrases are necessary here because the sentence is straightforward.

I might also consider if there's a more commonly used term in Thai for "world." "โลก" (loak) is the standard word for world, so that's fine. Another consideration is the flow of the sentence in Thai. Thai often places the main subject first, followed by the verb, which is already reflected in "เทคโนโลยีเชื่อมต่อโลก."

I don't see any grammatical issues with the translation. It's clear and concise, effectively conveying that technology connects the world. I don't think there's a better way to phrase it that would be more accurate or polite. So the final translation is "เทคโนโลยีเชื่อมต่อโลก."
</think>

เทคโนโลยีเชื่อมต่อโลก


====================================================================================================
📌 Without System Message
📝 Output:
 <｜User｜>Translate this sentence into Thai: 'Technology connects the world.' <｜Assistant｜><think>
Alright, so I have to translate the sentence "Technology connects the world." into Thai. Let me think about how to approach this. First, I know that "Technology" in Thai is "เทคโนโลยี" or "เทคโนโลยี". The word "connects" means to connect or link things together, so in Thai, that could be "เชื่อม" or "ติดต่อ". Now, putting it together, I need a phrase that combines technology with connecting the world.

Hmm, maybe "เทคโนโลยี เชื่อมโลก" would work. Does that sound natural? Let me break it down. เทคโนโลยี is clear, and เชื่อมโลก means connecting the world. Yeah, that seems to make sense. I think that's correct. I don't think I need to add any other words because it's a concise translation. I don't recall any particles or additional words that are commonly used in this context. So, I believe "เทคโนโลยี เชื่อมโลก" is the right way to say "Technology connects the world." in Thai.
</think>

เทคโนโลยี เชื่อมโลก

In [ ]:
cot_fewshot_prompt = """Translate the following English sentence to Thai.

English: "She loves reading books."

Step-by-step:
1. Identify subject → "She"
2. Identify verb → "loves"
3. Identify object → "reading books"
4. Translate each:
   - "She" → "เธอ"
   - "loves" → "ชอบ"
   - "reading books" → "การอ่านหนังสือ"
5. Reorder in Thai → "เธอชอบอ่านหนังสือ"

Thai: เธอชอบอ่านหนังสือ

---

English: "I miss you."

Step-by-step:
"""

output = pipe(
    cot_fewshot_prompt,
    max_new_tokens=300,
    do_sample=True,
    top_k=50,
    top_p=0.9,
    temperature=0.7
)

print("Few-shot Output:\n", output[0]["generated_text"])

Few-shot Output:
 Translate the following English sentence to Thai.

English: "She loves reading books."

Step-by-step:
1. Identify subject → "She"
2. Identify verb → "loves"
3. Identify object → "reading books"
4. Translate each:
   - "She" → "เธอ"
   - "loves" → "ชอบ"
   - "reading books" → "การอ่านหนังสือ"
5. Reorder in Thai → "เธอชอบอ่านหนังสือ"

Thai: เธอชอบอ่านหนังสือ

---

English: "I miss you."

Step-by-step:
1. Identify subject → "I"
2. Identify verb → "miss"
3. Identify object → "you"
4. Translate each:
   - "I" → "ฉัน"
   - "miss" → "พลาด"
   - "you" → "คุณ"
5. Reorder in Thai → "ฉันพลาดคุณ"

Thai: ฉันพลาดคุณ

---

English: "He wants to go there."

Step-by-step:
1. Identify subject → "He"
2. Identify verb → "wants"
3. Identify object → "to go there"
4. Translate each:
   - "He" → "เขา"
   - "wants" → "ต้องการ"
   - "to go there" → "ไปนั่น"
5. Reorder in Thai → "เขาต้องการไปนั่น"

Thai: เขาต้องการไปนั่น

---

English: "They are studying."

Step-by-step:
1. Identify subject → "They"
2. Identify verb → "are studying"
3. Identify object → "nothing" (since no direct object; focus on the action)
4. Translate each:
   - "They" → "พวกเขาที่"
   - "are studying" → "กำลังอ่าน"
   - "nothing" → "ข้อมูลนั้นไม่มี"
5. Reorder in Thai → "พวกเขาที่กำลังอ่านข้อม

## Evaluation

### Dataset

In [ ]:
from datasets import load_dataset
from itertools import islice

dataset = load_dataset("glaiveai/reasoning-v1-20m", split="train", streaming=True)

small_dataset = list(islice(dataset, 10))

print(f"จำนวนที่โหลดได้: {len(small_dataset)}")
print(small_dataset[0])

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md:   0%|          | 0.00/1.73k [00:00<?, ?B/s]

Resolving data files:   0%|          | 0/709 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/709 [00:00<?, ?it/s]

จำนวนที่โหลดได้: 10
{'prompt': "What are the implications of the Eocene-Oligocene transition's increased sedimentation rates in the Olympic Peninsula's sedimentary basins on the regional paleogeography and the subsequent development of the Cascadia subduction zone's forearc geometry?", 'response': "<think>\nAlright, so I'm trying to figure out the implications of increased sedimentation rates during the Eocene-Oligocene transition in the Olympic Peninsula's sedimentary basins on the regional paleogeography and the development of the Cascadia subduction zone's forearc geometry. Hmm, that's a mouthful. Let's break it down step by step.\n\nFirst, I need to understand what the Eocene-Oligocene transition was like. I remember that this transition, around 33-34 million years ago, marked a significant change in Earth's climate. There was a cooling event, which led to the formation of Antarctic ice sheets. This cooling probably affected sea levels and ocean currents, which in turn could influence sedimentation.\n\nNow, the Olympic Peninsula is in the Pacific Northwest, USA. I think it's part of the Cascadia subduction zone, where the Juan de Fuca plate is being subducted under the North American plate. The forearc region is the area between the trench and the volcanic arc. So, the sedimentary basins in this area would be part of that forearc region.\n\nIncreased sedimentation rates during this period. Why would that happen? Well, maybe tectonic activity increased, causing more uplift or subsidence in the basins. Uplift in surrounding areas could lead to more erosion and sediment supply. Alternatively, changes in sea level might expose more land, leading to increased sediment load. Also, the climate cooling might have changed weathering patterns, producing more sediment.\n\nSo, what does this mean for the regional paleogeography? Paleogeography refers to the ancient geography, so increased sedimentation would imply that the basins were filling up more quickly. This could mean that the basins were subsiding faster, or that there was a lot more sediment being deposited. Subsidence could be due to tectonic forces, like extension or loading from nearby volcanic activity.\n\nAs for the forearc geometry of the Cascadia subduction zone, the sedimentation rates would affect how the forearc basin developed. The forearc basin's geometry is influenced by factors like sediment supply, tectonic deformation, and the subduction process itself. If there was a lot of sediment coming in, it might fill the basin, making it shallower or wider. This could influence how the subduction zone behaves, perhaps affecting the angle of subduction or the formation of accretionary wedges.\n\nI'm also thinking about how the sediment load might affect the mechanical properties of the subducting plate. More sediment could make the plate more buoyant or change the friction along the subduction interface, which might influence seismic activity or the formation of the volcanic arc.\n\nAnother point is the role of sea level changes. During the Eocene-Oligocene transition, sea levels dropped due to ice sheet formation. This would expose coastal areas, leading to more erosion and sediment transport into the basins. This regression could also change the shoreline configuration, affecting the paleogeography by perhaps creating deltas or coastal plains.\n\nAdditionally, the increased sedimentation could provide a record of tectonic activity. If the sediments are composed of certain types of rocks or have specific structures, they might indicate tectonic uplift, volcanic activity, or changes in the subduction zone's dynamics.\n\nI should also consider the timing. The Eocene-Oligocene transition is a period when the Cascadia subduction zone was starting to take shape. So, the sedimentation rates at that time would set the stage for how the forearc developed in subsequent periods. If the basins were filled rapidly, it might have influenced the geometry by creating a certain structure that affected later tectonic processes.\n\nMoreover, the composition of the sediments could give clues about the surrounding geology. For example, if the sediments are rich in volcanic material, it suggests nearby volcanic activity, which ties into the subduction zone's evolution. Alternatively, sediment provenance could indicate the source areas, which might have been uplifted during this time.\n\nI'm also thinking about the relationship between sedimentation and subduction dynamics. High sedimentation rates might lead to a thicker sediment layer on the subducting plate, which can affect the behavior of the subduction zone. It might influence the occurrence of earthquakes, the formation of melanges, or the development of the accretionary prism.\n\nIn terms of paleogeography, the increased sedimentation could have led to the formation of specific landforms or the drowning of certain areas. It could also affect the connectivity between different basins or the formation of straits and inlets, which would be important for understanding the regional geography at the time.\n\nI should also think about the broader implications for the Cascadia system. If the forearc geometry was influenced by sedimentation rates, this could have long-term effects on how the subduction zone operates. For example, a well-developed accretionary prism could influence the seismic hazard or the distribution of volcanoes in the arc.\n\nLastly, I need to consider how geologists study these sedimentation rates. They probably look at cores, seismic data, and stratigraphic sections to determine sediment thickness and composition over time. These data points help reconstruct the paleogeography and tectonic history of the region.\n\nPutting it all together, increased sedimentation during the Eocene-Oligocene transition in the Olympic Peninsula likely led to significant changes in the regional paleogeography, such as basin filling and shoreline changes. This, in turn, would have influenced the development of the Cascadia forearc by shaping the basin geometry, affecting tectonic processes, and setting the stage for future subduction zone dynamics.\n</think>\n\nThe increased sedimentation rates during the Eocene-Oligocene transition in the Olympic Peninsula's sedimentary basins had profound implications for both the regional paleogeography and the development of the Cascadia subduction zone's forearc geometry. Here's a structured summary of the implications:\n\n### Regional Paleogeography:\n1. **Basin Dynamics**: The rapid sedimentation likely led to the filling of basins, possibly due to subsidence or increased sediment supply from tectonic uplift or climate-induced erosion. This process would have changed the topography, affecting local drainage systems and landforms.\n\n2. **Sea Level Changes**: The global cooling and associated sea level drop exposed coastal areas, increasing erosion and sediment transport. This regression could have resulted in the formation of deltas or coastal plains, altering shorelines and paleogeographic features.\n\n3. **Sediment Composition**: The sediments deposited during this period provide insights into the surrounding geology, including volcanic activity and source areas, which were likely influenced by tectonic uplift.\n\n### Cascadia Subduction Zone's Forearc Geometry:\n1. **Forearc Development**: The increased sediment load influenced the forearc basin's geometry, potentially making it shallower or wider. This could have affected the subduction angle and the formation of accretionary wedges.\n\n2. **Tectonic and Seismic Implications**: High sedimentation rates may have altered the mechanical properties of the subducting plate, affecting buoyancy and friction, which could influence seismic activity and the volcanic arc's formation.\n\n3. **Long-term Evolution**: The sedimentation during this period set the stage for the forearc's future development, influencing subsequent tectonic processes and the structure of the accretionary prism.\n\n### Broader Implications:\n- **Subduction Dynamics**: The sediment layer's thickness on the subducting plate could affect subduction behavior, including earthquake occurrence and melange formation.\n- **Volcanic Activity**: Sediment composition might indicate nearby volcanic activity, tying into the subduction zone's evolution.\n\nIn conclusion, the increased sedimentation during the Eocene-Oligocene transition significantly shaped the Olympic Peninsula's paleogeography and laid the foundation for the Cascadia forearc's structure, influencing its tectonic and seismic characteristics."}

In [ ]:
for i, sample in enumerate(small_dataset):
    print(f"\n🔹 Sample {i+1}")
    for key, value in sample.items():
        print(f"{key}: {value[:200] if isinstance(value, str) else value}")

🔹 Sample 1
prompt: What are the implications of the Eocene-Oligocene transition's increased sedimentation rates in the Olympic Peninsula's sedimentary basins on the regional paleogeography and the subsequent development
response: <think>
Alright, so I'm trying to figure out the implications of increased sedimentation rates during the Eocene-Oligocene transition in the Olympic Peninsula's sedimentary basins on the regional pale

🔹 Sample 2
prompt: What are the optimal conditions for using microbial-induced calcite precipitation as a sustainable method for self-healing concrete, specifically in terms of bacterial strain selection, nutrient suppl
response: <think>
Okay, so I'm trying to figure out the optimal conditions for using microbial-induced calcite precipitation (MICP) in self-healing concrete. This is for a large infrastructure project, so I nee

🔹 Sample 3
prompt: What is the most effective method for teaching student pilots to recognize and respond to the subtle differences in aircraft handling characteristics that occur when transitioning from a dry adiabatic
response: <think>
Okay, so I'm trying to figure out the best way to teach student pilots about the differences in aircraft handling when moving from a dry adiabatic lapse rate to a saturated one, especially at

🔹 Sample 4
prompt: What is the optimal ratio of polylactic acid (PLA) to polyhydroxyalkanoates (PHA) in a biodegradable plastic blend to achieve a degradation rate of 50% within 6 months in a marine environment with ave
response: <think>
Okay, so I'm trying to figure out the optimal ratio of PLA to PHA in a biodegradable plastic blend that would degrade 50% in 6 months under specific marine conditions. The temperatures there r

🔹 Sample 5
prompt: How can a polycentric urban structure, with multiple secondary cities and a range of small to medium-sized towns, be effectively integrated into a regional transportation network to promote more equit
response: <think>
Okay, so I have this question about integrating a polycentric urban structure into a regional transportation network. Let me try to break this down. The region has a strong core-periphery patt

🔹 Sample 6
prompt: What is the most efficient way to implement a 64-bit Montgomery multiplication algorithm in ARM assembly language, taking into account the use of the NEON SIMD instructions and the Cortex-A53's pipeli
response: <think>
Okay, so I'm trying to figure out how to implement a 64-bit Montgomery multiplication efficiently in ARM assembly, especially using NEON SIMD instructions on a Cortex-A53. I'm a bit new to thi

🔹 Sample 7
prompt: How can I effectively integrate the concept of intersectionality into my lesson plans on the Civil Rights Movement, specifically when teaching about the roles of women and LGBTQ+ individuals in the mo
response: <think>
Okay, so I need to figure out how to integrate intersectionality into my lesson plans about the Civil Rights Movement, especially focusing on women and LGBTQ+ individuals. I also have to think

🔹 Sample 8
prompt: How can the supervaluationist approach to vagueness be reconciled with the Sorites paradox, particularly in cases where the penumbral connections between adjacent degrees of a soritical series are con
response: <think>
Okay, so I'm trying to understand how the supervaluationist approach to vagueness deals with the Sorites paradox, especially when the connections between different degrees in a soritical serie

🔹 Sample 9
prompt: What are the specific parameters and G-code settings required to optimize the performance of a Haas VF-2 CNC milling machine when machining a complex aluminum alloy part with a combination of 3D curve
response: <think>
Okay, so I'm trying to figure out how to optimize the performance of a Haas VF-2 CNC milling machine for a complex aluminum alloy part. The part has 3D curved surfaces and high-aspect-ratio fe

🔹 Sample 10
prompt: What are the implications of the recent discovery of the SARS-CoV-2 N-protein's ability to inhibit the activity of the host cell's autophagy-related gene 5 (ATG5) on the development of COVID-19 vaccin
response: <think>
Okay, so I'm trying to understand the implications of the SARS-CoV-2 N-protein's ability to inhibit ATG5 on COVID-19 vaccines that target the nucleocapsid protein, especially in immunocompromi

### Evaluation process

### Cleaning Text

In [ ]:
def extract_predictions(text: str) -> str:
    """ตัด output ให้เหลือเฉพาะตั้งแต่หลัง </think> เป็นต้นไป """
    split_point = text.lower().find("</think>")
    if split_point != -1:
        return text[split_point + len("</think>"):].strip()
    return text.strip()  # fallback ถ้าไม่เจอ </think>

In [ ]:
def extract_ref(text: str) -> str:
    """ตัดข้อความตั้งแต่หลัง </think> เป็นต้นไป"""
    split_point = text.lower().find("</think>")
    if split_point != -1:
        return text[split_point + len("</think>"):].strip()
    return text.strip()  # fallback ถ้าไม่มี </think>

small_dataset_clean = [
    {
        "prompt": item["prompt"],
        "response": extract_ref(item["response"])
    }
    for item in small_dataset
]

In [ ]:
print(small_dataset[3])

{'prompt': 'What is the optimal ratio of polylactic acid (PLA) to polyhydroxyalkanoates (PHA) in a biodegradable plastic blend to achieve a degradation rate of 50% within 6 months in a marine environment with average temperatures ranging from 15°C to 25°C and pH levels between 7.5 and 8.5?', 'response': "<think>\nOkay, so I'm trying to figure out the optimal ratio of PLA to PHA in a biodegradable plastic blend that would degrade 50% in 6 months under specific marine conditions. The temperatures there range from 15°C to 25°C, and the pH is between 7.5 and 8.5. \n\nFirst, I need to understand what PLA and PHA are. PLA, polylactic acid, is a biodegradable thermoplastic derived from renewable resources like corn starch or sugarcane. It's commonly used in 3D printing and packaging. PHA, polyhydroxyalkanoates, are a family of biodegradable polyesters produced through bacterial fermentation. They're known for their biocompatibility and are often used in medical applications as well as packaging.\n\nI know that both PLA and PHA are biodegradable, but their degradation rates can vary based on environmental conditions. So, the goal here is to blend them in such a way that the mixture degrades 50% in six months in a marine setting. \n\nI remember that PLA degrades mainly through hydrolysis, which means it breaks down when exposed to water. The process is influenced by temperature and pH. Higher temperatures and more acidic or basic pH levels can accelerate hydrolysis. However, in marine environments, the pH is slightly alkaline, around 8, which might affect PLA's degradation rate. \n\nPHA, on the other hand, tends to degrade more readily in aqueous environments, especially when there are microorganisms present. Marine environments are rich in bacteria, so PHA might break down faster than PLA in such conditions. \n\nI think the key here is to balance the two materials so that their combined degradation meets the 50% target. If PLA is more resistant to degradation in marine conditions, maybe a higher proportion of PHA is needed to speed things up. Conversely, if PHA degrades too quickly, maybe a higher PLA content would slow it down to prevent the blend from breaking down too fast.\n\nI should look into how each polymer behaves in marine environments. From what I recall, PLA has a slower degradation rate in seawater compared to PHA. Studies have shown that PHA can degrade within a few months in marine environments, whereas PLA might take longer, possibly several years, especially under less extreme conditions.\n\nSo, if we want a 50% degradation in six months, maybe a higher PHA content is necessary. Let's say, for example, that PHA can degrade 80% in six months by itself, and PLA only 20%. To get an average of 50%, we might need a blend that's more PHA than PLA. \n\nBut I also need to consider how blending affects the overall degradation. Sometimes, blending can create a synergistic effect, but other times, it might not be a straightforward average. The physical properties of the blend, like crystallinity and molecular weight, can influence how each polymer interacts with the environment.\n\nAnother factor is the surface area. If the blend has a higher PHA content, it might provide more sites for microbial attack, accelerating the degradation of the entire blend. Conversely, a higher PLA content might form a more resistant matrix, slowing down the overall process.\n\nI should also think about the manufacturing process. Are there any constraints on the ratio for extrusion or injection molding? If the ratio is too high in one polymer, it might affect the mechanical properties or processability. But since the question is about degradation rate, maybe we can focus just on that aspect.\n\nLooking for existing studies or data on PLA/PHA blends in marine environments would be ideal. I remember reading that a 50/50 blend can show moderate degradation, but maybe a higher PHA content is needed for the 50% target. Alternatively, perhaps a 30/70 PLA/PHA ratio would achieve the desired rate.\n\nI should also consider the pH range. PLA is more sensitive to acidic conditions, but since marine environments are slightly alkaline, PLA's degradation might be slower than in acidic environments. PHA, being more versatile, might be less affected by the pH in this range.\n\nTemperature is another variable. Between 15°C and 25°C, the higher end of the temperature range could accelerate degradation. So, the blend's performance at the upper limit might determine the ratio needed to ensure 50% degradation within six months.\n\nIn summary, considering PHA's faster degradation in marine conditions, a higher PHA content in the blend would likely be necessary. I'm thinking a ratio where PHA is dominant, maybe around 70%, to ensure that the blend meets the 50% degradation target. However, without specific data, this is an educated guess based on the general properties of each polymer.\n</think>\n\nThe optimal ratio of PLA to PHA in a biodegradable plastic blend to achieve a 50% degradation rate within 6 months in a marine environment with temperatures between 15°C and 25°C and a pH of 7.5 to 8.5 is estimated to be a 30:70 PLA to PHA ratio. This conclusion is based on the understanding that PHA degrades more rapidly in marine conditions due to microbial activity, while PLA is more resistant. A higher PHA content ensures the blend meets the degradation target without overly compromising mechanical properties."}

In [ ]:
print(small_dataset_clean[3])

{'prompt': 'What is the optimal ratio of polylactic acid (PLA) to polyhydroxyalkanoates (PHA) in a biodegradable plastic blend to achieve a degradation rate of 50% within 6 months in a marine environment with average temperatures ranging from 15°C to 25°C and pH levels between 7.5 and 8.5?', 'response': 'The optimal ratio of PLA to PHA in a biodegradable plastic blend to achieve a 50% degradation rate within 6 months in a marine environment with temperatures between 15°C and 25°C and a pH of 7.5 to 8.5 is estimated to be a 30:70 PLA to PHA ratio. This conclusion is based on the understanding that PHA degrades more rapidly in marine conditions due to microbial activity, while PLA is more resistant. A higher PHA content ensures the blend meets the degradation target without overly compromising mechanical properties.'}

### Evaluation Method

In [ ]:
import time
import evaluate
import pandas as pd

bleu = evaluate.load("bleu")
rouge = evaluate.load("rouge")
bertscore = evaluate.load("bertscore")

In [ ]:
# เตรียม inputs และ references จาก small_dataset
inputs = [item["prompt"] for item in small_dataset]

# วนลูปเพื่อ generate prediction จาก prompt
predictions = []
for prompt in inputs:
    messages = [
        {"role": "system", "content": "You are a thoughtful assistant who explains your reasoning before giving a final answer."},
        {"role": "user", "content": prompt}
    ]

    result = safe_flexible_generate(
        messages=messages,
        tokenizer=tokenizer,
        model=model,
        is_chat=True,
        do_sample=True,
        top_k=50,
        top_p=0.9,
        temperature=0.7
    )
    predictions.append(result.strip())

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

In [ ]:
# เตรียม reference จาก small_dataset_clean
references = [item["response"] for item in small_dataset_clean]
predictions_clean = [extract_predictions(p) for p in predictions]

# คำนวณ BLEU
bleu_score = bleu.compute(
    predictions=predictions_clean,
    references=[[r] for r in references]  # ต้องใส่ list ซ้อน list
)

# คำนวณ ROUGE
rouge_score = rouge.compute(
    predictions=predictions_clean,
    references=references
)

# คำนวณ BERTScore (ใช้ภาษาอังกฤษ)
bert_result = bertscore.compute(
    predictions=predictions_clean,
    references=references,
    lang="en"
)

# แสดงผลลัพธ์รวม
print("✅ Evaluation Results:")
print(f"- BLEU Precision: {bleu_score['bleu']:.4f}")
print(f"- ROUGE-1 F1:     {rouge_score['rouge1']:.4f}")
print(f"- ROUGE-2 F1:     {rouge_score['rouge2']:.4f}")
print(f"- ROUGE-L F1:     {rouge_score['rougeL']:.4f}")
print(f"- BERTScore F1:   {sum(bert_result['f1']) / len(bert_result['f1']):.4f}")

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/482 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
WARNING:huggingface_hub.file_download:Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/1.42G [00:00<?, ?B/s]

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

✅ Evaluation Results:
- BLEU Precision: 0.1889
- ROUGE-1 F1:     0.4938
- ROUGE-2 F1:     0.1832
- ROUGE-L F1:     0.2735
- BERTScore F1:   0.8844

### BERTScore

In [ ]:
print("✅ BERTScore Average:")
print(f"- Precision: {sum(bert_result['precision']) / len(bert_result['precision']):.4f}")
print(f"- Recall:    {sum(bert_result['recall']) / len(bert_result['recall']):.4f}")
print(f"- F1:        {sum(bert_result['f1']) / len(bert_result['f1']):.4f}")

✅ BERTScore Average:
- Precision: 0.8855
- Recall:    0.8835
- F1:        0.8844

In [ ]:
# สร้าง DataFrame เปรียบเทียบ
df_compare = pd.DataFrame({
    "Prediction": predictions_clean,
    "Reference": references
})

# แสดงผลทั้งหมดแบบเต็มข้อความ
pd.set_option("display.max_colwidth", None)
display(df_compare)

,Prediction,Reference
0,"The Eocene-Oligocene transition in the Olympic Peninsula's sedimentary basins, characterized by increased sedimentation rates, has several significant implications for regional paleogeography and the development of the Cascadia subduction zone's forearc geometry. \n\n**Implications for Paleogeography:**\n1. **Sedimentary Record and Tectonic Activity:** The increased sedimentation likely reflects a period of active tectonism, where more sediment was carried into basins, possibly due to rising landforms or enhanced riverine activity. This period also coincided with the westward movement of the Pacific Plate, leading to subduction and volcanic activity, which contributed to erosion and sediment transport.\n\n2. **Stratigraphic Sequences and Habitats:** The accumulation of sediment could have created distinct stratigraphic units and influenced the development of marine and terrestrial environments, potentially altering habitats and shaping the region's paleogeography.\n\n**Implications for the Cascadia Subduction Zone:**\n1. **Forearc Geometry and Subduction History:** The increased sedimentation contributed to the development of the Cascadia subduction zone's forearc by adding more material, which may have affected the forearc's geometry. This could include changes in the shape of ridges, troughs, and the overall structure of the overlying crust.\n\n2. **Subduction Process and Tectonic History:** This sedimentation provides a geological record that aids in understanding the subduction process and the evolution of the Cascadia subduction zone. It helps in mapping the subduction history and the movement of the Pacific Plate, contributing to the region's tectonic stability and seismic activity.\n\n**Conclusion:**\nThe increased sedimentation during the Eocene-Oligocene transition in the Olympic Peninsula's basins not only shaped the region's paleogeography but also influenced the development of the Cascadia subduction zone's forearc. This period's geological record is crucial for understanding the region's tectonic history and ongoing processes, offering insights into the evolution of its geological features.","The increased sedimentation rates during the Eocene-Oligocene transition in the Olympic Peninsula's sedimentary basins had profound implications for both the regional paleogeography and the development of the Cascadia subduction zone's forearc geometry. Here's a structured summary of the implications:\n\n### Regional Paleogeography:\n1. **Basin Dynamics**: The rapid sedimentation likely led to the filling of basins, possibly due to subsidence or increased sediment supply from tectonic uplift or climate-induced erosion. This process would have changed the topography, affecting local drainage systems and landforms.\n\n2. **Sea Level Changes**: The global cooling and associated sea level drop exposed coastal areas, increasing erosion and sediment transport. This regression could have resulted in the formation of deltas or coastal plains, altering shorelines and paleogeographic features.\n\n3. **Sediment Composition**: The sediments deposited during this period provide insights into the surrounding geology, including volcanic activity and source areas, which were likely influenced by tectonic uplift.\n\n### Cascadia Subduction Zone's Forearc Geometry:\n1. **Forearc Development**: The increased sediment load influenced the forearc basin's geometry, potentially making it shallower or wider. This could have affected the subduction angle and the formation of accretionary wedges.\n\n2. **Tectonic and Seismic Implications**: High sedimentation rates may have altered the mechanical properties of the subducting plate, affecting buoyancy and friction, which could influence seismic activity and the volcanic arc's formation.\n\n3. **Long-term Evolution**: The sedimentation during this period set the stage for the forearc's future development, influencing subsequent tectonic processes and the structure of the accretionary prism.\n\n### Broader Implications:\n- **Subduction Dynamics**: The sediment layer's thickness on the subducting plate could affect subduction behavior, including earthquake occurrence and melange formation.\n- **Volcanic Activity**: Sediment composition might indicate nearby volcanic activity, tying into the subduction zone's evolution.\n\nIn conclusion, the increased sedimentation during the Eocene-Oligocene transition significantly shaped the Olympic Peninsula's paleogeography and laid the foundation for the Cascadia forearc's structure, influencing its tectonic and seismic characteristics."
1,"To optimize microbial-induced calcite precipitation (MICP) for self-healing concrete in large-scale infrastructure projects, consider the following:\n\n### Bacterial Strain Selection:\n- **Bacillus sp.** and **Bacillus pseudofuscous** are commonly used due to their efficiency in calcite precipitation.\n- **Pseudomonas aeruginosa** is another effective strain, particularly in nutrient-rich environments.\n\n### Nutrient Supplementation:\n- **Calcium and Carbonate Ions**: Provide these as supplements to ensure bacterial growth. Use calcium carbonate or other sources to maintain optimal levels.\n- **Nitrogen and Phosphate**: Essential for bacterial growth; consider organic or inorganic sources based on bacterial preference and environmental impact.\n\n### Environmental Factors:\n- **Temperature**: Optimal growth between 20-30°C ensures bacterial activity.\n- **pH**: Maintain a slightly alkaline environment, around 8.5, to support bacterial growth; adjust pH with bicarbonate or lime if necessary.\n- **Moisture Content**: Keep relative humidity between 60-80% to facilitate bacterial growth without causing issues like efflorescence.\n\n### Application Method:\n- Apply bacterial solutions as a slurry or spray for efficient coverage in large-scale projects.\n- Ensure uniform application to maintain consistency across the structure.\n\n### Additional Considerations:\n- **Cost-Effectiveness**: Use locally available nutrients and efficient application methods to reduce costs.\n- **Longevity**: Select strains that produce stable calcite and ensure adhesion to the concrete surface.\n- **Competitive Exclusion**: Use selective growth media to suppress competing microorganisms.\n- **Monitoring**: Implement automated systems for consistent application and condition monitoring.\n- **Strength and Durability**: Assess how calcite content affects concrete strength, aiming for enhanced compressive and flexural strength.\n\nBy integrating these elements, MICP can become a sustainable solution, reducing maintenance and enhancing infrastructure durability.","To determine the optimal conditions for using microbial-induced calcite precipitation (MICP) in self-healing concrete for large infrastructure projects, the following key considerations are essential:\n\n### 1. Bacterial Strain Selection\n- **Optimal Strains**: Use bacteria such as *Sporosarcina pasteurii*, *Bacillus subtilis*, or *Lysinibacillus sphaericus*. These strains are effective due to their high urease production, spore-forming ability, and tolerance to alkaline environments.\n- **Characteristics**: Select strains that can survive in high pH conditions, form biofilms for protection, and adhere well to concrete surfaces.\n\n### 2. Nutrient Supplementation\n- **Urea and Calcium Sources**: Provide urea as a nitrogen source and calcium ions (e.g., from calcium nitrate or calcium chloride) for calcite formation.\n- **Additional Nutrients**: Consider supplements like yeast extract to enhance bacterial growth, ensuring they do not adversely affect concrete properties.\n\n### 3. Environmental Factors\n- **pH Tolerance**: Ensure bacteria can thrive in the high alkalinity of concrete (pH 9-12).\n- **Temperature and Moisture**: Optimize for temperatures between 20-30°C and maintain sufficient moisture for bacterial activity without causing concrete degradation.\n\n### 4. Application Methodology\n- **Incorporation**: Integrate bacteria during concrete mixing or apply as a surface treatment. Ensure even distribution for effective crack healing.\n- **Scalability and Cost**: Develop methods that are cost-effective and compatible with large-scale construction processes.\n\n### 5. Longevity and Testing\n- **Durability**: Assess long-term viability of bacteria within concrete, ensuring they remain effective over decades.\n- **Testing**: Conduct crack healing tests and monitor durability, strength, and water tightness to validate effectiveness.\n\n### 6. Considerations and Challenges\n- **Potential Issues**: Monitor for over-production of calcite and ensure bacterial byproducts do not compromise concrete integrity.\n- **Environmental Impact**: Prevent contamination of surrounding materials or ecosystems.\n\nBy addressing these factors, MICP can be effectively utilized to enhance concrete durability, reduce maintenance costs, and provide a sustainable solution for large infrastructure projects."
2,"The most effective method for teaching student pilots to recognize and respond to the subtleties of transitioning between dry and saturated adiabatic lapse rates, especially in orographic regions, involves a multifaceted approach:\n\n1. **Theoretical Education**: Begin with foundational knowledge of adiabatic lapse rates, distinguishing between dry and saturated conditions, and understanding orographic enhancement. This provides pilots with the essential understanding necessary to interpret atmospheric changes.\n\n2. **Simulator Training**: Utilize flight simulators to allow pilots to experience the effects of different atmospheric conditions on aircraft performance, including changes in lift, drag, and stall characteristics without the need for repeated real-world exposure.\n\n3. **Field Training**: Conduct practical flight training in regions prone to orographic enhancement. This hands-on experience helps pilots apply theoretical knowledge in actual operational scenarios.\n\n4. **Case Studies and Scenario-Based Training**: Study real incidents where pilots encountered these conditions and their responses. This approach offers practical examples and reinforces the impact of atmospheric changes on flight operations.\n\n5. **Performance Considerations**: Discuss how these conditions affect aircraft performance, such as altered lift efficiency, drag dynamics, and stall behavior, ensuring pilots can adjust their techniques accordingly.\n\nBy integrating these elements, pilots gain both the knowledge and skills needed to handle the unique challenges of transitioning between atmospheric conditions, ensuring safer and more effective flight operations.","To effectively teach student pilots about handling aircraft during transitions from dry to saturated adiabatic lapse rates at high altitudes, especially with orographic enhancement, a comprehensive and multi-faceted approach is recommended:\n\n1. **Foundational Knowledge**: Begin with the basics of lapse rates, explaining how dry and saturated conditions affect temperature changes with altitude. Emphasize the role of latent heat release in saturated air and its impact on air density.\n\n2. **Visual and Interactive Tools**: Use graphs, animations, and simulators to illustrate temperature-altitude profiles and the effects of orographic lifting. Simulators can mimic scenarios where lapse rate changes occur, allowing students to practice adjustments in real-time.\n\n3. **Case Studies and Real Data**: Incorporate real-life incidents where lapse rate changes affected flights. Use METARs and forecasts to teach predictive skills, helping students anticipate conditions.\n\n4. **Flight Planning and Instruments**: Train students to use flight planning tools that account for lapse rates. Teach them to interpret aircraft instruments to recognize air density changes.\n\n5. **Hands-On Practice**: Utilize simulated flights or actual training flights to observe conditions, though note the dependency on specific weather events. Instructors can highlight relevant scenarios during flights.\n\n6. **Checklists and Decision Trees**: Develop guidelines for actions during transitions, such as altitude adjustments or performance monitoring, to help students respond effectively.\n\n7. **Meteorology Integration**: Collaborate with meteorologists to deepen understanding of weather dynamics, enabling better anticipation of conditions.\n\n8. **Assessment and Application**: Use scenario-based exams and flight checks to assess understanding. Integrate this training into broader curriculum modules to cover related high-altitude factors like oxygen levels and icing.\n\nBy combining these elements, student pilots will gain a thorough understanding of lapse rate impacts on aircraft performance, enhancing their ability to navigate safely in varying conditions."
3,"The optimal ratio of polylactic acid (PLA) to polyhydroxyalkanoates (PHA) in a biodegradable plastic blend to achieve a 50% degradation rate within 6 months in a marine environment is approximately 60% PLA to 40% PHA. This ratio balances the degradation rates of both polymers under the given conditions, ensuring the blend degrades at a moderate rate without being too fast or slow.","The optimal ratio of PLA to PHA in a biodegradable plastic blend to achieve a 50% degradation rate within 6 months in a marine environment with temperatures between 15°C and 25°C and a pH of 7.5 to 8.5 is estimated to be a 30:70 PLA to PHA ratio. This conclusion is based on the understanding that PHA degrades more rapidly in marine conditions due to microbial activity, while PLA is more resistant. A higher PHA content ensures the blend meets the degradation target without overly compromising mechanical properties."
4,"To integrate a polycentric urban structure into a regional transportation network and promote equitable economic growth while reducing peripherality, consider the following comprehensive strategy:\n\n1. **Enhance Public Transportation Infrastructure:**\n - **Rail Network Expansion:** Develop a robust railway system connecting secondary cities and peripheral towns, reducing reliance on private vehicles and fostering economic connections.\n - **Public Transit Upgrades:** Expand bus services and invest in bike-sharing and pedestrian-friendly infrastructure in both core and peripheral areas to improve connectivity and accessibility.\n\n2. **Promote Economic Development in Peripheral Areas:**\n - **Job Creation in Secondary Cities:** Encourage the development of job opportunities in secondary cities, possibly through targeted industrial zones or innovation hubs, to attract investment and reduce the need for long-distance commuting.\n\n3. **Implement Affordable Transportation Solutions:**\n - **Tiered Fare Structures:** Introduce fare policies based on distance or time to ensure affordability for a diverse population, making public transit accessible to a wider range of income levels.\n\n4. **Leverage Technology and Remote Work:**\n - **Job Sharing and Remote Work Programs:** Promote flexible work arrangements to reduce the demand for long-distance commuting and alleviate pressure on the transportation system.\n\n5. **Inclusive Community Engagement:**\n - **Public Involvement in Planning:** Involve residents in the transportation planning process to ensure that the system meets the needs of all community members, fostering a sense of ownership and inclusion.\n\n6. **Complete Street Designs:**\n - **Infrastructure for All Modes:** Implement street designs that prioritize pedestrian and cyclist safety and accessibility, reducing the need for private vehicle reliance and enhancing community livability.\n\nBy integrating these strategies, the transportation network will become a catalyst for equitable economic growth, connecting peripheral areas with the core while fostering a more inclusive and sustainable regional development.","Integrating a polycentric urban structure into a regional transportation network to promote equitable economic growth and reduce peripherality involves a comprehensive and multi-faceted approach. Here's a structured summary of the key strategies:\n\n1. **Comprehensive Regional Planning:**\n - Develop a regional plan identifying key nodes (secondary cities and towns) and corridors to create a network of hubs rather than a single core.\n - Use a hub-and-spoke model with multiple mini-hubs connected to smaller towns, ensuring connectivity between hubs.\n\n2. **Transportation Infrastructure Development:**\n - Invest in public transportation such as buses and trains for inter-city connections and local services for smaller towns.\n - Upgrade existing infrastructure to avoid sprawl and enhance efficiency.\n\n3. **Frequency and Reliability:**\n - Increase the frequency and reliability of public transport to encourage usage and economic activity.\n\n4. **Multimodal Transportation Integration:**\n - Integrate different transport modes (bus, train, bike-share) with seamless transitions, using smart systems for real-time management and integrated ticketing.\n\n5. **Economic Development Strategies:**\n - Align transportation improvements with economic incentives for businesses in secondary cities.\n - Promote mixed-use developments around transport hubs through zoning and land-use planning.\n\n6. **Governance and Coordination:**\n - Establish a regional authority for coordinated planning and involve local communities in decision-making.\n\n7. **Sustainability Initiatives:**\n - Use green technologies like electric vehicles and promote walking and cycling with improved infrastructure.\n\n8. **Funding and Partnerships:**\n - Explore public-private partnerships, grants, and innovative financing mechanisms to fund projects.\n\n9. **Monitoring and Evaluation:**\n - Implement metrics to measure economic growth, transportation usage, and peripherality reduction, adjusting strategies as needed.\n\n10. **Geographical Considerations:**\n - Tailor solutions to the region's geography, focusing on key corridors and population centers.\n\nBy integrating these strategies, the region can reduce peripherality, distribute economic growth more equitably, and enhance overall connectivity and sustainability."

### Evaluation Size

In [ ]:
# กำหนดรอบที่ต้องการ evaluate
eval_checkpoints = {5, 10}  # เพิ่มเฉพาะรอบ 5 และ 10 แบบเฉพาะเจาะจง

# เตรียม input และ reference
inputs = [item["prompt"] for item in small_dataset]
references_raw = [item["response"] for item in small_dataset]

# เตรียม clean reference ล่วงหน้า
refs_clean_all = [extract_ref(r) for r in references_raw]

# เตรียมสำหรับเก็บผล
predictions = []
times = []

# zero-shot prompt
Role_prompt = "You are a thoughtful assistant who explains your reasoning before giving a final answer."

# วนลูป generate ทีละ prompt
for i, prompt in enumerate(inputs):
    messages = [
        {"role": "system", "content": Role_prompt},
        {"role": "user", "content": prompt}
    ]

    start_time = time.time()

    result = safe_flexible_generate(
        messages=messages,
        tokenizer=tokenizer,
        model=model,
        is_chat=True,     # ใช้ chat format
        do_sample=True,
        top_k=50,
        top_p=0.9,
        temperature=0.7
    )

    duration = time.time() - start_time
    times.append(duration)
    predictions.append(result.strip())

    # แสดงเวลาทุกรอบ
    print(f"🕒 [{i+1}/{len(inputs)}] Generated in {duration:.2f} seconds")

    # ตรวจรอบ evaluate
    if (i + 1) in eval_checkpoints or (i + 1) % 20 == 0:
        preds_clean = [extract_predictions(p) for p in predictions]
        refs_clean = refs_clean_all[:i+1]

        bleu_score = bleu.compute(
            predictions=preds_clean,
            references=[[r] for r in refs_clean]
        )
        rouge_score = rouge.compute(
            predictions=preds_clean,
            references=refs_clean
        )
        bert_result = bertscore.compute(
            predictions=preds_clean,
            references=refs_clean,
            lang="en"
        )

        avg_bert_f1 = sum(bert_result['f1']) / len(bert_result['f1'])
        total_time = sum(times)

        print(f"\n🎯 Evaluation @ {i+1} samples")
        print(f"- BLEU Precision: {bleu_score['bleu']:.4f}")
        print(f"- ROUGE-1 F1:     {rouge_score['rouge1']:.4f}")
        print(f"- ROUGE-2 F1:     {rouge_score['rouge2']:.4f}")
        print(f"- ROUGE-L F1:     {rouge_score['rougeL']:.4f}")
        print(f"- BERTScore F1:   {avg_bert_f1:.4f}")
        print(f"⏱️ Total time up to {i+1} samples: {total_time:.2f} seconds\n")

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

🕒 [1/10] Generated in 126.54 seconds

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

🕒 [2/10] Generated in 139.28 seconds

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

🕒 [3/10] Generated in 86.42 seconds

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

🕒 [4/10] Generated in 223.43 seconds
🕒 [5/10] Generated in 104.16 seconds

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

🎯 Evaluation @ 5 samples
- BLEU Precision: 0.1605
- ROUGE-1 F1:     0.4804
- ROUGE-2 F1:     0.1597
- ROUGE-L F1:     0.2463
- BERTScore F1:   0.8815
⏱️ Total time up to 5 samples: 679.82 seconds

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

🕒 [6/10] Generated in 135.44 seconds

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

🕒 [7/10] Generated in 133.18 seconds

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

🕒 [8/10] Generated in 90.46 seconds

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

🕒 [9/10] Generated in 125.71 seconds
🕒 [10/10] Generated in 103.16 seconds

🎯 Evaluation @ 10 samples
- BLEU Precision: 0.2080
- ROUGE-1 F1:     0.4995
- ROUGE-2 F1:     0.1760
- ROUGE-L F1:     0.2604
- BERTScore F1:   0.8827
⏱️ Total time up to 10 samples: 1267.77 seconds

https://colab.research.google.com/drive/1mRJwsh_2zhg2V-eyVI2JqpXwcXMu7X78?usp=sharing

🕒 [1/121] Generated in 124.29 seconds
🕒 [2/121] Generated in 102.40 seconds
🕒 [3/121] Generated in 88.91 seconds
🕒 [4/121] Generated in 380.29 seconds
🕒 [5/121] Generated in 126.15 seconds🎯 Evaluation @ 5 samples
- BLEU Precision: 0.1599
- ROUGE-1 F1:     0.4925
- ROUGE-2 F1:     0.1712
- ROUGE-L F1:     0.2560
- BERTScore F1:   0.8849
⏱️ Total time up to 5 samples: 822.05 seconds

🕒 [6/121] Generated in 1142.19 seconds
🕒 [7/121] Generated in 115.49 seconds
🕒 [8/121] Generated in 99.28 seconds
🕒 [9/121] Generated in 105.81 seconds
🕒 [10/121] Generated in 110.54 seconds

🎯 Evaluation @ 10 samples
- BLEU Precision: 0.1820
- ROUGE-1 F1:     0.4775
- ROUGE-2 F1:     0.1711
- ROUGE-L F1:     0.2515
- BERTScore F1:   0.8759
⏱️ Total time up to 10 samples: 2395.35 seconds

🕒 [11/121] Generated in 130.22 seconds
🕒 [12/121] Generated in 91.40 seconds
🕒 [13/121] Generated in 80.74 seconds
🕒 [14/121] Generated in 55.15 seconds
🕒 [15/121] Generated in 133.46 seconds
🕒 [16/121] Generated in 83.09 seconds
🕒 [17/121] Generated in 135.73 seconds
🕒 [18/121] Generated in 109.75 seconds
🕒 [19/121] Generated in 156.60 seconds
🕒 [20/121] Generated in 111.56 seconds

🎯 Evaluation @ 20 samples
- BLEU Precision: 0.1886
- ROUGE-1 F1:     0.4805
- ROUGE-2 F1:     0.1680
- ROUGE-L F1:     0.2492
- BERTScore F1:   0.8788
⏱️ Total time up to 20 samples: 3483.05 seconds

🕒 [21/121] Generated in 118.64 seconds
🕒 [22/121] Generated in 78.48 seconds
🕒 [23/121] Generated in 146.90 seconds
🕒 [24/121] Generated in 110.15 seconds
🕒 [25/121] Generated in 115.79 seconds
🕒 [26/121] Generated in 125.35 seconds
🕒 [27/121] Generated in 155.67 seconds
🕒 [28/121] Generated in 100.50 seconds
🕒 [29/121] Generated in 73.94 seconds
🕒 [30/121] Generated in 126.63 seconds
🕒 [31/121] Generated in 100.99 seconds
🕒 [32/121] Generated in 90.95 seconds
🕒 [33/121] Generated in 93.77 seconds
🕒 [34/121] Generated in 90.96 seconds
🕒 [35/121] Generated in 121.47 seconds
🕒 [36/121] Generated in 106.19 seconds
🕒 [37/121] Generated in 91.20 seconds
🕒 [38/121] Generated in 102.14 seconds
🕒 [39/121] Generated in 93.47 seconds
🕒 [40/121] Generated in 125.36 seconds

🎯 Evaluation @ 40 samples
- BLEU Precision: 0.1785
- ROUGE-1 F1:     0.4862
- ROUGE-2 F1:     0.1655
- ROUGE-L F1:     0.2482
- BERTScore F1:   0.8773
⏱️ Total time up to 40 samples: 5651.60 seconds

🕒 [41/121] Generated in 93.49 seconds
🕒 [42/121] Generated in 118.37 seconds
🕒 [43/121] Generated in 194.91 seconds
🕒 [44/121] Generated in 67.96 seconds
🕒 [45/121] Generated in 92.79 seconds
🕒 [46/121] Generated in 52.71 seconds
🕒 [47/121] Generated in 103.06 seconds
🕒 [48/121] Generated in 109.42 seconds
🕒 [49/121] Generated in 81.24 seconds
🕒 [50/121] Generated in 49.53 seconds
🕒 [51/121] Generated in 137.48 seconds
🕒 [52/121] Generated in 102.98 seconds
🕒 [53/121] Generated in 106.34 seconds
🕒 [54/121] Generated in 110.33 seconds
🕒 [55/121] Generated in 135.55 seconds
🕒 [56/121] Generated in 88.82 seconds
🕒 [57/121] Generated in 121.04 seconds
🕒 [58/121] Generated in 81.75 seconds
🕒 [59/121] Generated in 82.84 seconds
🕒 [60/121] Generated in 95.57 seconds

🎯 Evaluation @ 60 samples
- BLEU Precision: 0.1747
- ROUGE-1 F1:     0.4841
- ROUGE-2 F1:     0.1654
- ROUGE-L F1:     0.2460
- BERTScore F1:   0.8780
⏱️ Total time up to 60 samples: 7677.76 seconds

🕒 [61/121] Generated in 54.18 seconds
🕒 [62/121] Generated in 58.46 seconds
🕒 [63/121] Generated in 88.81 seconds
🕒 [64/121] Generated in 73.54 seconds
🕒 [65/121] Generated in 101.49 seconds
🕒 [66/121] Generated in 77.22 seconds
🕒 [67/121] Generated in 96.12 seconds
🕒 [68/121] Generated in 102.74 seconds
🕒 [69/121] Generated in 119.32 seconds
🕒 [70/121] Generated in 99.24 seconds
🕒 [71/121] Generated in 129.31 seconds
🕒 [72/121] Generated in 85.39 seconds
🕒 [73/121] Generated in 69.23 seconds
🕒 [74/121] Generated in 82.78 seconds
🕒 [75/121] Generated in 119.57 seconds
🕒 [76/121] Generated in 184.11 seconds
🕒 [77/121] Generated in 84.40 seconds
🕒 [78/121] Generated in 327.81 seconds
🕒 [79/121] Generated in 128.40 seconds
🕒 [80/121] Generated in 95.49 seconds

🎯 Evaluation @ 80 samples
- BLEU Precision: 0.1799
- ROUGE-1 F1:     0.4913
- ROUGE-2 F1:     0.1705
- ROUGE-L F1:     0.2509
- BERTScore F1:   0.8799
⏱️ Total time up to 80 samples: 9855.38 seconds

🕒 [81/121] Generated in 81.87 seconds
🕒 [82/121] Generated in 443.35 seconds
🕒 [83/121] Generated in 96.29 seconds
🕒 [84/121] Generated in 177.68 seconds
🕒 [85/121] Generated in 120.02 seconds
🕒 [86/121] Generated in 89.00 seconds
🕒 [87/121] Generated in 116.35 seconds
🕒 [88/121] Generated in 98.50 seconds
🕒 [89/121] Generated in 104.94 seconds
🕒 [90/121] Generated in 74.98 seconds
🕒 [91/121] Generated in 91.57 seconds
🕒 [92/121] Generated in 97.92 seconds
🕒 [93/121] Generated in 145.71 seconds
🕒 [94/121] Generated in 118.04 seconds
🕒 [95/121] Generated in 74.66 seconds
🕒 [96/121] Generated in 86.49 seconds
🕒 [97/121] Generated in 91.88 seconds
🕒 [98/121] Generated in 117.61 seconds
🕒 [99/121] Generated in 105.62 seconds
🕒 [100/121] Generated in 117.49 seconds

🎯 Evaluation @ 100 samples
- BLEU Precision: 0.1832
- ROUGE-1 F1:     0.4873
- ROUGE-2 F1:     0.1691
- ROUGE-L F1:     0.2500
- BERTScore F1:   0.8809
⏱️ Total time up to 100 samples: 12305.33 seconds

🕒 [101/121] Generated in 79.48 seconds
🕒 [102/121] Generated in 87.32 seconds
🕒 [103/121] Generated in 127.16 seconds
🕒 [104/121] Generated in 635.01 seconds
🕒 [105/121] Generated in 103.45 seconds
🕒 [106/121] Generated in 125.83 seconds
🕒 [107/121] Generated in 158.80 seconds
🕒 [108/121] Generated in 88.37 seconds
🕒 [109/121] Generated in 87.40 seconds
🕒 [110/121] Generated in 110.91 seconds
🕒 [111/121] Generated in 124.76 seconds
🕒 [112/121] Generated in 88.48 seconds
🕒 [113/121] Generated in 81.68 seconds
🕒 [114/121] Generated in 86.70 seconds
🕒 [115/121] Generated in 112.47 seconds
🕒 [116/121] Generated in 112.58 seconds
🕒 [117/121] Generated in 133.92 seconds
🕒 [118/121] Generated in 111.53 seconds

#Deepseek Llama vs Deepseek Qwen

In [ ]:
qwen_model_name = "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B"

qwen_tokenizer = AutoTokenizer.from_pretrained(qwen_model_name)
qwen_model = AutoModelForCausalLM.from_pretrained(
    qwen_model_name,
    quantization_config=bnb_config,
    device_map="auto",
)

qwen_pipe = pipeline(
    "text-generation",
    model=qwen_model,
    tokenizer=qwen_tokenizer,
    trust_remote_code=True
)

tokenizer_config.json:   0%|          | 0.00/3.07k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/680 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/28.1k [00:00<?, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

model-00001-of-000002.safetensors:   0%|          | 0.00/8.61G [00:00<?, ?B/s]

model-00002-of-000002.safetensors:   0%|          | 0.00/6.62G [00:00<?, ?B/s]

Sliding Window Attention is enabled but not implemented for `sdpa`; unexpected results may be encountered.

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/181 [00:00<?, ?B/s]

Device set to use cuda:0

In [ ]:
qwen_predictions = []
qwen_times = []

for i, prompt in enumerate(inputs):
    messages = [
        {"role": "system", "content": Role_prompt},
        {"role": "user", "content": prompt}
    ]

    start_time = time.time()

    result = safe_flexible_generate(
        messages=messages,
        tokenizer=qwen_tokenizer,
        model=qwen_model,
        is_chat=True,
        do_sample=True,
        top_k=50,
        top_p=0.9,
        temperature=0.7
    )

    duration = time.time() - start_time
    qwen_times.append(duration)
    qwen_predictions.append(result.strip())

    print(f"[QWEN] 🕒 [{i+1}/{len(inputs)}] Generated in {duration:.2f} seconds")

Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.

[QWEN] 🕒 [1/10] Generated in 118.36 seconds

Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.

[QWEN] 🕒 [2/10] Generated in 119.61 seconds

Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.

[QWEN] 🕒 [3/10] Generated in 63.78 seconds

Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.

[QWEN] 🕒 [4/10] Generated in 80.47 seconds

Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.

[QWEN] 🕒 [5/10] Generated in 103.31 seconds

Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.

[QWEN] 🕒 [6/10] Generated in 147.81 seconds

Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.

[QWEN] 🕒 [7/10] Generated in 117.15 seconds

Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.

[QWEN] 🕒 [8/10] Generated in 89.87 seconds

Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.

[QWEN] 🕒 [9/10] Generated in 128.45 seconds
[QWEN] 🕒 [10/10] Generated in 96.91 seconds

In [ ]:
qwen_preds_clean = [extract_predictions(p) for p in qwen_predictions]

# BLEU
qwen_bleu = bleu.compute(
    predictions=qwen_preds_clean,
    references=[[r] for r in refs_clean_all]
)

# ROUGE
qwen_rouge = rouge.compute(
    predictions=qwen_preds_clean,
    references=refs_clean_all
)

# BERTScore
qwen_bert = bertscore.compute(
    predictions=qwen_preds_clean,
    references=refs_clean_all,
    lang="en"
)

# สรุปผลลัพธ์
print("\n📊 Qwen Evaluation Results:")
print(f"- BLEU Precision: {qwen_bleu['bleu']:.4f}")
print(f"- ROUGE-1 F1:     {qwen_rouge['rouge1']:.4f}")
print(f"- ROUGE-2 F1:     {qwen_rouge['rouge2']:.4f}")
print(f"- ROUGE-L F1:     {qwen_rouge['rougeL']:.4f}")
print(f"- BERTScore F1:   {sum(qwen_bert['f1']) / len(qwen_bert['f1']):.4f}")

📊 Qwen Evaluation Results:
- BLEU Precision: 0.1878
- ROUGE-1 F1:     0.5103
- ROUGE-2 F1:     0.1883
- ROUGE-L F1:     0.2829
- BERTScore F1:   0.8879

In [ ]:
df_compare = pd.DataFrame({
    "Metric": ["BLEU", "ROUGE-1", "ROUGE-2", "ROUGE-L", "BERTScore F1"],
    "LLaMA": [
        bleu_score['bleu'],
        rouge_score['rouge1'],
        rouge_score['rouge2'],
        rouge_score['rougeL'],
        sum(bert_result['f1']) / len(bert_result['f1'])
    ],
    "Qwen": [
        qwen_bleu['bleu'],
        qwen_rouge['rouge1'],
        qwen_rouge['rouge2'],
        qwen_rouge['rougeL'],
        sum(qwen_bert['f1']) / len(qwen_bert['f1'])
    ]
})

df_compare

         Metric     LLaMA      Qwen
0          BLEU  0.207982  0.187774
1       ROUGE-1  0.499475  0.510281
2       ROUGE-2  0.175955  0.188264
3       ROUGE-L  0.260406  0.282926
4  BERTScore F1  0.882686  0.887898

### Zero-prompt vs Chat-prompt

In [ ]:
results_zero_shot = []
results_chat_role = []

zero_shot_prompt = "You are a thoughtful assistant who explains your reasoning before giving a final answer."

for item in small_dataset:
    prompt = item["prompt"]

    # ✅ แบบ Zero-shot (prompt ธรรมดา)
    full_prompt = f"{zero_shot_prompt}\n\n{prompt}"
    result_zero = safe_flexible_generate(
        prompt=full_prompt,
        tokenizer=tokenizer,
        model=model,
        is_chat=False,
        top_k=50,
        top_p=0.9,
        temperature=0.7
    )
    results_zero_shot.append(result_zero.strip())

    # ✅ แบบ Chat with Role
    messages = [
        {"role": "system", "content": zero_shot_prompt},
        {"role": "user", "content": prompt}
    ]
    result_chat = safe_flexible_generate(
        messages=messages,
        tokenizer=tokenizer,
        model=model,
        is_chat=True,
        top_k=50,
        top_p=0.9,
        temperature=0.7
    )
    results_chat_role.append(result_chat.strip())


# Clean
preds_zero_clean = [extract_predictions(p) for p in results_zero_shot]
preds_chat_clean = [extract_predictions(p) for p in results_chat_role]
refs_clean = [item["response"] for item in small_dataset_clean]

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

NameError: name 'bleu' is not defined

In [ ]:
# Compute metrics
bleu_zero = bleu.compute(
    predictions=preds_zero_clean,
    references=[[r] for r in refs_clean]
)
bleu_chat = bleu.compute(
    predictions=preds_chat_clean,
    references=[[r] for r in refs_clean]
)

rouge_zero = rouge.compute(
    predictions=preds_zero_clean,
    references=refs_clean
)
rouge_chat = rouge.compute(
    predictions=preds_chat_clean,
    references=refs_clean
)

bert_zero = bertscore.compute(
    predictions=preds_zero_clean,
    references=refs_clean,
    lang="en",
    model_type="bert-base-uncased"
)
bert_chat = bertscore.compute(
    predictions=preds_chat_clean,
    references=refs_clean,
    lang="en",
    model_type="bert-base-uncased"
)

# คำนวณ BERTScore F1 เฉลี่ยอย่างชัดเจน
bert_zero_f1 = sum(bert_zero["f1"]) / len(bert_zero["f1"])
bert_chat_f1 = sum(bert_chat["f1"]) / len(bert_chat["f1"])

# Compare
print("เปรียบเทียบ Zero-shot vs Chat แบบใส่ Role ทั้งคู่")
print(f"🔹 BLEU Precision:  {bleu_zero['bleu']:.4f} vs {bleu_chat['bleu']:.4f}")
print(f"🔹 ROUGE-L:         {rouge_zero['rougeL']:.4f} vs {rouge_chat['rougeL']:.4f}")
print(f"🔹 BERTScore F1:    {bert_zero_f1:.4f} vs {bert_chat_f1:.4f}")

เปรียบเทียบ Zero-shot vs Chat แบบใส่ Role ทั้งคู่
🔹 BLEU Precision:  0.1994 vs 0.2341
🔹 ROUGE-L:         0.2825 vs 0.2788
🔹 BERTScore F1:    0.7173 vs 0.7241

### Zero-prompt vs Chat-prompt, No Role

In [ ]:
results_zero_shot_noRole = []
results_chat_user_only = []

for item in small_dataset:
    prompt = item["prompt"]

    # ✅ Zero-shot: ใช้ prompt อย่างเดียว (ไม่มี system)
    result_zero = safe_flexible_generate(
        prompt=prompt,
        tokenizer=tokenizer,
        model=model,
        is_chat=False,
        top_k=50,
        top_p=0.9,
        temperature=0.7
    )
    results_zero_shot_noRole.append(result_zero.strip())

    # ✅ Chat format (ไม่มี system, มีแค่ user)
    messages = [
        {"role": "user", "content": prompt}
    ]
    result_chat = safe_flexible_generate(
        messages=messages,
        tokenizer=tokenizer,
        model=model,
        is_chat=True,
        top_k=50,
        top_p=0.9,
        temperature=0.7
    )
    results_chat_user_only.append(result_chat.strip())

# Clean
preds_zero_clean = [extract_predictions(p) for p in results_zero_shot_noRole]
preds_chat_clean = [extract_predictions(p) for p in results_chat_user_only]
refs_clean = [item["response"] for item in small_dataset_clean]

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

In [ ]:
# Compute metrics
bleu_zero = bleu.compute(
    predictions=preds_zero_clean,
    references=[[r] for r in refs_clean]
)
bleu_chat = bleu.compute(
    predictions=preds_chat_clean,
    references=[[r] for r in refs_clean]
)

rouge_zero = rouge.compute(
    predictions=preds_zero_clean,
    references=refs_clean
)
rouge_chat = rouge.compute(
    predictions=preds_chat_clean,
    references=refs_clean
)

bert_zero = bertscore.compute(
    predictions=preds_zero_clean,
    references=refs_clean,
    lang="en",
    model_type="bert-base-uncased"
)
bert_chat = bertscore.compute(
    predictions=preds_chat_clean,
    references=refs_clean,
    lang="en",
    model_type="bert-base-uncased"
)

# คำนวณ BERTScore F1 เฉลี่ยอย่างชัดเจน
bert_zero_f1 = sum(bert_zero["f1"]) / len(bert_zero["f1"])
bert_chat_f1 = sum(bert_chat["f1"]) / len(bert_chat["f1"])

# Compare
print("เปรียบเทียบ Zero-shot vs Chat (ไม่มีการกำหนด Role)")
print(f"🔹 BLEU Precision: {bleu_zero['bleu']:.4f} vs {bleu_chat['bleu']:.4f}")
print(f"🔹 ROUGE-L:        {rouge_zero['rougeL']:.4f} vs {rouge_chat['rougeL']:.4f}")
print(f"🔹 BERTScore F1:   {bert_zero_f1:.4f} vs {bert_chat_f1:.4f}")

เปรียบเทียบ Zero-shot vs Chat (ไม่มีการกำหนด Role)
🔹 BLEU Precision: 0.1712 vs 0.1791
🔹 ROUGE-L:        0.2694 vs 0.2616
🔹 BERTScore F1:   0.6884 vs 0.7003